### ISSUE TITLE
bash: line 1:  2758 Broken pipe             gsort /dev/stdi

### ISSUE THREAD

**Issue by colindaven** [brentp/smoove#10]
This tool looks interesting. Unfortunately I have got a broken pipe here. Any ideas? 

cheers

```
smoove call --name my-cohort --fasta mm10.fa -p 24 --genotype 2018/*.bam


smoove
smoove version: 0.1.1

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools [only required for CRAM input]

  [ ] cnvnator [per-sample CNV calls]
  [Y] mosdepth [extra filtering of split and discordant files for better scaling]
  [Y] svtyper [required to genotype SV calls]
  [ ] only needed for large cohorts.

Available sub-commands are below. Each can be run with -h for additional help.

call     : call lumpy (and optionally svtyper) after filtering bams
cnvnator : call cnvnator and make bedpe files needed by lumpy
genotype : parallelize svtyper on an input VCF
merge    : merge and sort (using svtools) calls from multiple samples



chr1    3499500 10_1    N       N]chr1:3502382] 803.17  .       SVTYPE=BND;STRANDS=++:28;IMPRECISE;CIPOS=-30,493;CIEND=-30,440;CIPOS95=0,65;CIEND95=-6,49;MATEID=10_2;EVENT=10;SU=28;PE=28;SR=0;PRPOS=2.70159e-114,1.46202e-110,7.912e-107,4.28173e-103,2.31714e-99,1.25397e-95,6.78609e-92,3.67242e-88,1.9874e-84,1.07552e-80,5.8204e-77,3.14982e-73,1.70459e-69,9.22471e-66,4.99213e-62,2.70159e-58,1.46202e-54,7.912e-51,4.28173e-47,2.31714e-43,1.25397e-39,6.78609e-36,3.67242e-32,1.9874e-28,1.07552e-24,5.8204e-21,3.14982e-17,1.70459e-13,9.22471e-10,4.99213e-06,0.0270159,0.0268671,0.0264696,0.0260316,0.0255955,0.0251392,0.0246599,0.0242488,0.023836,0.0234309,0.0230691,0.0226806,0.0222766,0.0218454,0.0214265,0.0210461,0.0206284,0.0202198,0.0198055,0.0194162,0.0189595,0.0185523,0.0181619,0.0177404,0.0173078,0.0168982,0.016479,0.016064,0.0156542,0.015261,0.0148371,0.014441,0.0140658,0.0136267,0.0132059,0.0128246,0.0124325,0.0120775,0.0117239,0.011377,0.0110161,0.0106586,0.0103091,0.00995568,0.00959137,0.00925548,0.00890342,0.00857818,0.00825755,0.00794713,0.00764008,0.00732881,0.00702068,0.00673065,0.00643526,0.00615398,0.00587929,0.00560019,0.00532831,0.00506626,0.00480944,0.00456869,0.0043298,0.00410166,0.00388139,0.00367075,0.00347533,0.00328142,0.00309962,0.00292223,0.00275228,0.0025791,0.00242519,0.00227027,0.0021241,0.00198483,0.001854,0.00172882,0.00160979,0.00149507,0.00139487,0.00129264,0.00119918,0.00110738,0.00101756,0.000936398,0.00086104,0.000792708,0.000726921,0.000664278,0.000606374,0.000552343,0.000503382,0.000458068,0.000415701,0.000376475,0.000339617,0.000305637,0.000274844,0.000247198,0.000221861,0.000199165,0.000177372,0.000157974,0.000141232,0.000125699,0.000111399,9.85373e-05,8.70645e-05,7.66083e-05,6.78187e-05,5.93595e-05,5.20847e-05,4.55676e-05,3.96626e-05,3.45641e-05,2.99867e-05,2.59841e-05,2.23284e-05,1.93263e-05,1.67073e-05,1.43628e-05,1.22903e-05,1.05346e-05,8.96253e-06,7.6346e-06,6.4986e-06,5.4744e-06,4.60133e-06,3.87705e-06,3.24366e-06,2.70822e-06,2.25683e-06,1.8925e-06,1.57752e-06,1.30833e-06,1.08108e-06,8.96271e-07,7.3432e-07,6.02916e-07,4.97674e-07,4.09085e-07,3.34632e-07,2.71163e-07,2.21535e-07,1.80124e-07,1.45624e-07,1.17969e-07,9.4471e-08,7.58373e-08,6.09299e-08,4.91589e-08,3.90797e-08,3.11977e-08,2.4714e-08,1.94699e-08,1.5365e-08,1.2223e-08,9.60779e-09,7.51215e-09,5.86979e-09,4.58549e-09,3.5866e-09,2.79164e-09,2.15689e-09,1.65507e-09,1.28573e-09,9.88158e-10,7.57412e-10,5.81571e-10,4.4047e-10,3.34414e-10,2.52372e-10,1.91394e-10,1.44873e-10,1.09316e-10,8.23134e-11,6.21852e-11,4.65345e-11,3.44572e-11,2.59412e-11,1.94634e-11,1.44291e-11,1.07885e-11,8.0525e-12,5.89042e-12,4.30916e-12,3.17853e-12,2.35175e-12,1.71309e-12,1.25475e-12,9.19597e-13,6.59802e-13,4.79813e-13,3.47029e-13,2.49125e-13,1.80384e-13,1.31155e-13,9.55025e-14,6.82948e-14,4.88779e-14,3.53156e-14,2.52632e-14,1.79468e-14,1.27578e-14,9.05813e-15,6.3348e-15,4.46943e-15,3.18047e-15,2.21115e-15,1.5293e-15,1.07217e-15,7.56342e-16,5.30031e-16,3.67055e-16,2.55774e-16,1.77899e-16,1.23089e-16,8.5249e-17,5.84118e-17,3.97219e-17,2.76493e-17,1.91236e-17,1.30787e-17,8.8759e-18,6.00032e-18,4.09378e-18,2.78746e-18,1.88011e-18,1.29156e-18,8.77123e-19,5.96473e-19,4.04114e-19,2.70977e-19,1.8264e-19,1.21861e-19,8.20197e-20,5.47005e-20,3.67335e-20,2.45787e-20,1.64415e-20,1.12316e-20,7.57422e-21,5.08122e-21,3.32812e-21,2.12035e-21,1.39523e-21,9.13988e-22,5.89313e-22,3.84421e-22,2.50529e-22,1.61229e-22,1.04243e-22,6.77332e-23,4.44397e-23,2.87998e-23,1.864e-23,1.20721e-23,7.81875e-24,5.05281e-24,3.27369e-24,2.08861e-24,1.33695e-24,8.49138e-25,5.56715e-25,3.53268e-25,2.29337e-25,1.4481e-25,9.16542e-26,5.76367e-26,3.66592e-26,2.33962e-26,1.5041e-26,9.58166e-27,6.01159e-27,3.83888e-27,2.39269e-27,1.49849e-27,9.34062e-28,5.89613e-28,3.63813e-28,2.24041e-28,1.39429e-28,8.57417e-29,5.33821e-29,3.33541e-29,2.06218e-29,1.30687e-29,7.90124e-30,4.84726e-30,2.95614e-30,1.84175e-30,1.11221e-30,6.78982e-31,4.0479e-31,2.49917e-31,1.54855e-31,9.51268e-32,5.91251e-32,3.61051e-32,2.17973e-32,1.32788e-32,7.71139e-33,4.58227e-33,2.80185e-33,1.71461e-33,1.02039e-33,6.04231e-34,3.55505e-34,2.13246e-34,1.30972e-34,7.66151e-35,4.65575e-35,2.86602e-35,1.70858e-35,1.0097e-35,6.0321e-36,3.567e-36,2.1412e-36,1.27041e-36,7.77967e-37,4.7062e-37,2.85298e-37,1.68192e-37,9.84941e-38,5.70223e-38,3.41127e-38,1.99364e-38,1.21009e-38,6.75695e-39,4.05855e-39,2.40418e-39,1.40459e-39,7.77761e-40,4.58138e-40,2.64714e-40,1.56773e-40,9.37389e-41,5.32638e-41,2.98002e-41,1.73222e-41,9.70192e-42,5.51008e-42,3.22889e-42,1.89011e-42,1.03528e-42,5.8241e-43,3.3663e-43,1.9572e-43,1.11378e-43,6.29898e-44,3.56341e-44,1.94292e-44,1.10666e-44,6.70378e-45,3.92749e-45,2.24267e-45,1.22399e-45,6.45122e-46,3.40928e-46,1.94801e-46,1.14199e-46,6.05034e-47,3.39284e-47,1.96506e-47,1.07935e-47,6.11379e-48,3.41676e-48,1.96721e-48,1.10485e-48,6.29622e-49,3.40607e-49,1.92051e-49,1.05206e-49,5.75393e-50,2.77991e-50,1.55241e-50,8.60034e-51,4.69738e-51,2.54025e-51,1.37124e-51,7.53411e-52,4.30459e-52,2.19281e-52,1.16873e-52,6.02522e-53,3.26204e-53,1.69353e-53,9.17354e-54,4.62996e-54,2.43701e-54,1.25143e-54,6.89171e-55,3.6873e-55,2.02414e-55,1.04648e-55,5.94477e-56,3.02977e-56,1.62637e-56,8.70896e-57,4.90973e-57,2.97553e-57,1.50816e-57,8.02432e-58,4.20941e-58,2.18565e-58,1.13857e-58,6.06832e-59,2.99054e-59,1.59267e-59,8.35459e-60,3.80918e-60,1.94796e-60,1.0327e-60,4.80546e-61,2.75697e-61,1.2978e-61,6.96713e-62,3.47509e-62,1.66729e-62,9.29273e-63,4.52757e-63,2.38359e-63,1.20478e-63,6.54023e-64,2.94425e-64,1.52629e-64,8.03573e-65,3.83115e-65,1.72679e-65,8.27078e-66,4.52162e-66,1.75739e-66,8.60736e-67,3.64952e-67,1.631e-67,7.63064e-68,2.9823e-68,1.54076e-68,6.77978e-69,2.77773e-69,1.44071e-69,6.84503e-70,2.73053e-70,1.10171e-70,4.84263e-71,1.6907e-71,7.42761e-72,3.37494e-72,1.57597e-72,6.6578e-73,3.19639e-73,1.65667e-73,7.4782e-74,3.82449e-74,1.54125e-74,5.00027e-75,1.91676e-75,8.27232e-76,2.85997e-76,1.18907e-76,4.23783e-77,2.01108e-77,8.13915e-78,2.65897e-78,1.01583e-78,3.57505e-79,1.25144e-79,5.69484e-80,1.71414e-80,4.16864e-81,1.33078e-81,5.37647e-82,1.37037e-82,6.2516e-83,1.94264e-83,3.64449e-84,1.52038e-84,5.02664e-85,1.3682e-85,2.30661e-86,3.57336e-87,9.59131e-88,2.01688e-88,6.33426e-89,2.03271e-89,4.08016e-90,9.23883e-91,4.76595e-92,5.3842e-93,3.56941e-94,2.45476e-95,8.8035e-96,3.13466e-97;PREND=4.45834e-36,4.41788e-34,4.3783e-32,4.33623e-30,4.29391e-28,4.24877e-26,4.20477e-24,3.05892e-22,2.2245e-20,1.61766e-18,1.17627e-16,6.28403e-15,1.81533e-13,5.24051e-12,1.51224e-10,3.20896e-09,6.80511e-08,1.44289e-06,2.24996e-05,0.000102605,0.000252666,0.000621229,0.00152678,0.00374898,0.00676908,0.00898792,0.0119246,0.0158225,0.0209727,0.0277981,0.0368104,0.0358233,0.0348283,0.0338461,0.0328908,0.0319298,0.0309809,0.0300339,0.0291085,0.0281601,0.0272545,0.0263437,0.0254329,0.0245556,0.023688,0.0228339,0.0220011,0.0211732,0.0203614,0.0195778,0.0188067,0.0180354,0.0172848,0.0165653,0.0158621,0.0151778,0.0145079,0.0138473,0.0132001,0.0125749,0.0119684,0.0113737,0.0108046,0.0102432,0.00971361,0.00919891,0.00869377,0.00821732,0.00775369,0.00730278,0.00686538,0.00645562,0.00606171,0.00567947,0.00531849,0.0049725,0.00464347,0.00433003,0.00402928,0.00374985,0.00348041,0.00323139,0.00299021,0.0027678,0.00255398,0.00235725,0.00217045,0.00199829,0.00183326,0.00168068,0.00153764,0.00140525,0.00128378,0.00116977,0.00106399,0.000964716,0.000873784,0.00079125,0.000714981,0.000643893,0.00057938,0.00052004,0.000465579,0.000416318,0.000371812,0.000331451,0.000294822,0.0002618,0.000231736,0.000204779,0.00018083,0.000159322,0.000139951,0.000122726,0.000107434,9.38303e-05,8.17858e-05,7.12031e-05,6.18305e-05,5.35717e-05,4.62646e-05,3.99468e-05,3.43725e-05,2.94957e-05,2.52733e-05,2.16149e-05,1.84424e-05,1.57056e-05,1.33585e-05,1.13133e-05,9.55771e-06,8.0696e-06,6.79223e-06,5.70182e-06,4.78311e-06,4.00013e-06,3.33376e-06,2.77036e-06,2.30041e-06,1.90304e-06,1.57341e-06,1.29609e-06,1.06465e-06,8.74737e-07,7.15732e-07,5.84027e-07,4.75165e-07,3.85879e-07,3.12355e-07,2.51798e-07,2.03277e-07,1.64196e-07,1.31754e-07,1.05519e-07,8.40543e-08,6.7072e-08,5.33244e-08,4.22676e-08,3.34159e-08,2.64049e-08,2.07746e-08,1.63294e-08,1.2828e-08,1.00368e-08,7.84364e-09,6.1159e-09,4.74665e-09,3.68023e-09,2.85934e-09,2.20835e-09,1.70042e-09,1.3081e-09,1.00154e-09,7.64654e-10,5.83504e-10,4.45059e-10,3.37188e-10,2.55243e-10,1.92911e-10,1.45384e-10,1.09468e-10,8.22507e-11,6.14436e-11,4.60103e-11,3.42652e-11,2.55185e-11,1.88973e-11,1.4011e-11,1.03581e-11,7.62938e-12,5.60471e-12,4.11141e-12,3.01175e-12,2.20371e-12,1.60818e-12,1.17081e-12,8.52383e-13,6.17941e-13,4.48153e-13,3.24963e-13,2.33773e-13,1.68601e-13,1.20912e-13,8.65785e-14,6.15664e-14,4.39551e-14,3.14304e-14,2.23873e-14,1.58975e-14,1.12896e-14,7.94128e-15,5.60483e-15,3.94439e-15,2.76595e-15,1.94235e-15,1.36476e-15,9.562e-16,6.66899e-16,4.65738e-16,3.23848e-16,2.24669e-16,1.55995e-16,1.07374e-16,7.43394e-17,5.11429e-17,3.49742e-17,2.40583e-17,1.6449e-17,1.11567e-17,7.58066e-18,5.13799e-18,3.48819e-18,2.36546e-18,1.60831e-18,1.08567e-18,7.31393e-19,4.91808e-19,3.29992e-19,2.21197e-19,1.48315e-19,9.96787e-20,6.68446e-20,4.44311e-20,2.95854e-20,1.9696e-20,1.29799e-20,8.61495e-21,5.67615e-21,3.78277e-21,2.49046e-21,1.64334e-21,1.07669e-21,7.10148e-22,4.63627e-22,3.04304e-22,1.97772e-22,1.29228e-22,8.40285e-23,5.44364e-23,3.55323e-23,2.3178e-23,1.49812e-23,9.59056e-24,6.15472e-24,3.97134e-24,2.55994e-24,1.64149e-24,1.04445e-24,6.66063e-25,4.2456e-25,2.67554e-25,1.70632e-25,1.08476e-25,6.87793e-26,4.34471e-26,2.76494e-26,1.73658e-26,1.08743e-26,6.87557e-27,4.29366e-27,2.69174e-27,1.68526e-27,1.05672e-27,6.56516e-28,4.10511e-28,2.54617e-28,1.58758e-28,9.83615e-29,6.10502e-29,3.78869e-29,2.35513e-29,1.45729e-29,8.95966e-30,5.54046e-30,3.39524e-30,2.08891e-30,1.28294e-30,7.90921e-31,4.84012e-31,2.9699e-31,1.81483e-31,1.10577e-31,6.72238e-32,4.09153e-32,2.50394e-32,1.52807e-32,9.18585e-33,5.54179e-33,3.3393e-33,2.02859e-33,1.21836e-33,7.32747e-34,4.39005e-34,2.61692e-34,1.56539e-34,9.41528e-35,5.63287e-35,3.33179e-35,1.98998e-35,1.1748e-35,6.96911e-36,4.13814e-36,2.44282e-36,1.45018e-36,8.66321e-37,5.14264e-37,3.02252e-37,1.78553e-37,1.05276e-37,6.16818e-38,3.61817e-38,2.16177e-38,1.26358e-38,7.38388e-39,4.28408e-39,2.45869e-39,1.43391e-39,8.43122e-40,4.96384e-40,2.87811e-40,1.67021e-40,9.5613e-41,5.49981e-41,3.1678e-41,1.80507e-41,1.04075e-41,5.95349e-42,3.43131e-42,1.99708e-42,1.15705e-42,6.53998e-43,3.75085e-43,2.10506e-43,1.18398e-43,6.88284e-44,3.94602e-44,2.2029e-44,1.23156e-44,6.94408e-45,3.87499e-45,2.19445e-45,1.25206e-45,7.08411e-46,3.92727e-46,2.16573e-46,1.1889e-46,6.63872e-47,3.67504e-47,2.05934e-47,1.11934e-47,6.25941e-48,3.39538e-48,1.86786e-48,1.01871e-48,5.48621e-49,2.95089e-49,1.61833e-49,8.74393e-50,4.94153e-50,2.76602e-50,1.51244e-50,8.30418e-51,4.55601e-51,2.50646e-51,1.37819e-51,7.60339e-52,4.12585e-52,2.2608e-52,1.23263e-52,6.57713e-53,3.55803e-53,1.87072e-53,1.01751e-53,5.29188e-54,2.86189e-54,1.54814e-54,7.976e-55,4.24675e-55,2.20381e-55,1.15012e-55,6.11432e-56,3.28796e-56,1.69132e-56,8.99595e-57,4.69e-57,2.49705e-57,1.30173e-57,6.81003e-58,3.46962e-58,1.76637e-58,9.07159e-59,4.6845e-59,2.35649e-59,1.18164e-59,5.93361e-60,3.10282e-60,1.59481e-60,7.93719e-61,4.06168e-61,1.9837e-61,1.0014e-61,4.65718e-62,2.34747e-62,1.13407e-62,5.75075e-63,2.8102e-63,1.39941e-63,6.45351e-64,2.92099e-64,1.4493e-64,6.7742e-65,3.34522e-65,1.55114e-65,7.65084e-66,3.36129e-66,1.70629e-66,7.66659e-67,3.61074e-67,1.6835e-67,8.38001e-68,3.67998e-68,1.7328e-68,8.20021e-69,3.52684e-69,1.51966e-69,7.02756e-70,2.98728e-70,1.29586e-70,5.71568e-71,2.58514e-71,1.07373e-71,4.63064e-72,1.97913e-72,7.45166e-73,2.89976e-73,1.12215e-73,4.63372e-74,1.6443e-74,5.84683e-75,2.35303e-75,8.15094e-76,2.96375e-76,1.16028e-76,4.0161e-77,1.19286e-77,3.65092e-78,1.13302e-78,3.26066e-79,1.02307e-79,3.61296e-80,8.93781e-81  GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB   0/1:83:248.79:-26,-1,-9:28:16:11:16:11:16:11:0:0:0:0.41 0/1:119:155.80:-18,-2,-14:29:20:8:20:8:20:8:0:0:0:0.29  0/1:200:398.58:-42,-2,-24:58:38:19:38:19:38:19:0:0:0:0.33       0/0:200:0.00:-0,-17,-55:56:56:0:55:0:34:0:0:21:0:0
chr1    3502382 10_2    N       N]chr1:3499500] 803.17  .       SVTYPE=BND;STRANDS=++:28;IMPRECISE;CIPOS=-30,440;CIEND=-30,493;CIPOS95=-6,49;CIEND95=0,65;MATEID=10_1;EVENT=10;SECONDARY;SU=28;PE=28;SR=0;PRPOS=4.45834e-36,4.41788e-34,4.3783e-32,4.33623e-30,4.29391e-28,4.24877e-26,4.20477e-24,3.05892e-22,2.2245e-20,1.61766e-18,1.17627e-16,6.28403e-15,1.81533e-13,5.24051e-12,1.51224e-10,3.20896e-09,6.80511e-08,1.44289e-06,2.24996e-05,0.000102605,0.000252666,0.000621229,0.00152678,0.00374898,0.00676908,0.00898792,0.0119246,0.0158225,0.0209727,0.0277981,0.0368104,0.0358233,0.0348283,0.0338461,0.0328908,0.0319298,0.0309809,0.0300339,0.0291085,0.0281601,0.0272545,0.0263437,0.0254329,0.0245556,0.023688,0.0228339,0.0220011,0.0211732,0.0203614,0.0195778,0.0188067,0.0180354,0.0172848,0.0165653,0.0158621,0.0151778,0.0145079,0.0138473,0.0132001,0.0125749,0.0119684,0.0113737,0.0108046,0.0102432,0.00971361,0.00919891,0.00869377,0.00821732,0.00775369,0.00730278,0.00686538,0.00645562,0.00606171,0.00567947,0.00531849,0.0049725,0.00464347,0.00433003,0.00402928,0.00374985,0.00348041,0.00323139,0.00299021,0.0027678,0.00255398,0.00235725,0.00217045,0.00199829,0.00183326,0.00168068,0.00153764,0.00140525,0.00128378,0.00116977,0.00106399,0.000964716,0.000873784,0.00079125,0.000714981,0.000643893,0.00057938,0.00052004,0.000465579,0.000416318,0.000371812,0.000331451,0.000294822,0.0002618,0.000231736,0.000204779,0.00018083,0.000159322,0.000139951,0.000122726,0.000107434,9.38303e-05,8.17858e-05,7.12031e-05,6.18305e-05,5.35717e-05,4.62646e-05,3.99468e-05,3.43725e-05,2.94957e-05,2.52733e-05,2.16149e-05,1.84424e-05,1.57056e-05,1.33585e-05,1.13133e-05,9.55771e-06,8.0696e-06,6.79223e-06,5.70182e-06,4.78311e-06,4.00013e-06,3.33376e-06,2.77036e-06,2.30041e-06,1.90304e-06,1.57341e-06,1.29609e-06,1.06465e-06,8.74737e-07,7.15732e-07,5.84027e-07,4.75165e-07,3.85879e-07,3.12355e-07,2.51798e-07,2.03277e-07,1.64196e-07,1.31754e-07,1.05519e-07,8.40543e-08,6.7072e-08,5.33244e-08,4.22676e-08,3.34159e-08,2.64049e-08,2.07746e-08,1.63294e-08,1.2828e-08,1.00368e-08,7.84364e-09,6.1159e-09,4.74665e-09,3.68023e-09,2.85934e-09,2.20835e-09,1.70042e-09,1.3081e-09,1.00154e-09,7.64654e-10,5.83504e-10,4.45059e-10,3.37188e-10,2.55243e-10,1.92911e-10,1.45384e-10,1.09468e-10,8.22507e-11,6.14436e-11,4.60103e-11,3.42652e-11,2.55185e-11,1.88973e-11,1.4011e-11,1.03581e-11,7.62938e-12,5.60471e-12,4.11141e-12,3.01175e-12,2.20371e-12,1.60818e-12,1.17081e-12,8.52383e-13,6.17941e-13,4.48153e-13,3.24963e-13,2.33773e-13,1.68601e-13,1.20912e-13,8.65785e-14,6.15664e-14,4.39551e-14,3.14304e-14,2.23873e-14,1.58975e-14,1.12896e-14,7.94128e-15,5.60483e-15,3.94439e-15,2.76595e-15,1.94235e-15,1.36476e-15,9.562e-16,6.66899e-16,4.65738e-16,3.23848e-16,2.24669e-16,1.55995e-16,1.07374e-16,7.43394e-17,5.11429e-17,3.49742e-17,2.40583e-17,1.6449e-17,1.11567e-17,7.58066e-18,5.13799e-18,3.48819e-18,2.36546e-18,1.60831e-18,1.08567e-18,7.31393e-19,4.91808e-19,3.29992e-19,2.21197e-19,1.48315e-19,9.96787e-20,6.68446e-20,4.44311e-20,2.95854e-20,1.9696e-20,1.29799e-20,8.61495e-21,5.67615e-21,3.78277e-21,2.49046e-21,1.64334e-21,1.07669e-21,7.10148e-22,4.63627e-22,3.04304e-22,1.97772e-22,1.29228e-22,8.40285e-23,5.44364e-23,3.55323e-23,2.3178e-23,1.49812e-23,9.59056e-24,6.15472e-24,3.97134e-24,2.55994e-24,1.64149e-24,1.04445e-24,6.66063e-25,4.2456e-25,2.67554e-25,1.70632e-25,1.08476e-25,6.87793e-26,4.34471e-26,2.76494e-26,1.73658e-26,1.08743e-26,6.87557e-27,4.29366e-27,2.69174e-27,1.68526e-27,1.05672e-27,6.56516e-28,4.10511e-28,2.54617e-28,1.58758e-28,9.83615e-29,6.10502e-29,3.78869e-29,2.35513e-29,1.45729e-29,8.95966e-30,5.54046e-30,3.39524e-30,2.08891e-30,1.28294e-30,7.90921e-31,4.84012e-31,2.9699e-31,1.81483e-31,1.10577e-31,6.72238e-32,4.09153e-32,2.50394e-32,1.52807e-32,9.18585e-33,5.54179e-33,3.3393e-33,2.02859e-33,1.21836e-33,7.32747e-34,4.39005e-34,2.61692e-34,1.56539e-34,9.41528e-35,5.63287e-35,3.33179e-35,1.98998e-35,1.1748e-35,6.96911e-36,4.13814e-36,2.44282e-36,1.45018e-36,8.66321e-37,5.14264e-37,3.02252e-37,1.78553e-37,1.05276e-37,6.16818e-38,3.61817e-38,2.16177e-38,1.26358e-38,7.38388e-39,4.28408e-39,2.45869e-39,1.43391e-39,8.43122e-40,4.96384e-40,2.87811e-40,1.67021e-40,9.5613e-41,5.49981e-41,3.1678e-41,1.80507e-41,1.04075e-41,5.95349e-42,3.43131e-42,1.99708e-42,1.15705e-42,6.53998e-43,3.75085e-43,2.10506e-43,1.18398e-43,6.88284e-44,3.94602e-44,2.2029e-44,1.23156e-44,6.94408e-45,3.87499e-45,2.19445e-45,1.25206e-45,7.08411e-46,3.92727e-46,2.16573e-46,1.1889e-46,6.63872e-47,3.67504e-47,2.05934e-47,1.11934e-47,6.25941e-48,3.39538e-48,1.86786e-48,1.01871e-48,5.48621e-49,2.95089e-49,1.61833e-49,8.74393e-50,4.94153e-50,2.76602e-50,1.51244e-50,8.30418e-51,4.55601e-51,2.50646e-51,1.37819e-51,7.60339e-52,4.12585e-52,2.2608e-52,1.23263e-52,6.57713e-53,3.55803e-53,1.87072e-53,1.01751e-53,5.29188e-54,2.86189e-54,1.54814e-54,7.976e-55,4.24675e-55,2.20381e-55,1.15012e-55,6.11432e-56,3.28796e-56,1.69132e-56,8.99595e-57,4.69e-57,2.49705e-57,1.30173e-57,6.81003e-58,3.46962e-58,1.76637e-58,9.07159e-59,4.6845e-59,2.35649e-59,1.18164e-59,5.93361e-60,3.10282e-60,1.59481e-60,7.93719e-61,4.06168e-61,1.9837e-61,1.0014e-61,4.65718e-62,2.34747e-62,1.13407e-62,5.75075e-63,2.8102e-63,1.39941e-63,6.45351e-64,2.92099e-64,1.4493e-64,6.7742e-65,3.34522e-65,1.55114e-65,7.65084e-66,3.36129e-66,1.70629e-66,7.66659e-67,3.61074e-67,1.6835e-67,8.38001e-68,3.67998e-68,1.7328e-68,8.20021e-69,3.52684e-69,1.51966e-69,7.02756e-70,2.98728e-70,1.29586e-70,5.71568e-71,2.58514e-71,1.07373e-71,4.63064e-72,1.97913e-72,7.45166e-73,2.89976e-73,1.12215e-73,4.63372e-74,1.6443e-74,5.84683e-75,2.35303e-75,8.15094e-76,2.96375e-76,1.16028e-76,4.0161e-77,1.19286e-77,3.65092e-78,1.13302e-78,3.26066e-79,1.02307e-79,3.61296e-80,8.93781e-81;PREND=2.70159e-114,1.46202e-110,7.912e-107,4.28173e-103,2.31714e-99,1.25397e-95,[smoove] 2018/03/11 22:22:40 bash: line 1:  2758 Broken pipe             gsort /dev/stdin /lager2/rcug/seqres/MM/mm10.fa.fai
      2759 Segmentation fault      (core dumped) | bcftools view -O z -c 1 -o my-cohort.genotyped.vcf.gz
[smoove] 2018/03/11 22:23:01 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:01 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:01 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:01 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:01  done
[smoove] 2018/03/11 22:23:02 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:02 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:02 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:02 Reading library metrics from /working2/rcug/scratch/tmp/tempclean-664002246/647993002svtype-lib...
[smoove] 2018/03/11 22:23:02  done
[smoove] 2018/03/11 22:23:04 chr2       1000000
chr2    2000000
chr2    4000000
panic: write |1: broken pipe

goroutine 3451837 [running]:
github.com/brentp/smoove/svtyper.checkWrite(0x0, 0x9e84a0, 0xc596569560)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:38 +0x4a
github.com/brentp/smoove/svtyper.Svtyper.func2(0xc509b4b740, 0xc4201be300, 0x4, 0x4, 0x7ffc40210697, 0x1e, 0xc4201b9130, 0xc4378701f8, 0xc437870220, 0xc4203fc1f8, ...)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:185 +0xb9
created by github.com/brentp/smoove/svtyper.Svtyper
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:155 +0x5e5

```

**Comment by brentp** [comment]
hmm, bcftools must be seeing something it doesn't like and closing the pipe. Let me see if I can make it output something more informative.

in your results directory, there will be a lumpy-cmd.sh script, you could try running that and piping to bcftools to get at the error more directly.

**Comment by colindaven** [comment]
OK, good hint about bcftools. I have been using soapdenovo via conda which requires an ancient bcftools, 0.1.19, so will upgrade bcftools again and retry. I'll have to setup a conda environment for soapdenovo. Will let you know if that works.

**Comment by colindaven** [comment]
So that worked nicely, I updated samtools to 1.5 and now have a `my-cohort.genotyped.vcf.gz` output file. Thanks!

**Comment by brentp** [comment]
thanks for following up. I added a note about this to the readme.
