### ISSUE TITLE
svtools merge issue

### ISSUE THREAD

**Issue by lee039** [brentp/smoove#103]
Hi,

I tried to merge files from 206 samples, and encountered this error.
Do you have any idea where should I look at?
The merging job ends prematurely, and left "merged.lsort.vcf" and "merged.sites.vcf.gz"

"merged.lsort.vcf" is the file that contains all the variants from 206 samples, and "merged.sites.vcf.gz" is the sorted file. I could see where it stops.

###error messege###
[smoove] 2020/02/23 12:14:38 starting with version 0.2.5
[smoove] 2020/02/23 12:14:38 merging 206 files
[smoove] 2020/02/23 12:14:38 finished sorting 206 files; merge starting.
[smoove] 2020/02/23 12:37:37 Traceback (most recent call last):
File "/home/u/f056598/miniconda2/bin/svtools", line 11, in
[smoove] 2020/02/23 12:37:37 sys.exit(main())
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/cli.py", line 79, in main
[smoove] 2020/02/23 12:37:37 sys.exit(args.entry_point(args))
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/lmerge.py", line 622, in run_from_args
[smoove] 2020/02/23 12:37:37 weighting_scheme=args.weighting_scheme)
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/lmerge.py", line 587, in l_cluster_by_line
[smoove] 2020/02/23 12:37:37 v_id = r_cluster(BP_l, sample_order, v_id, use_product, vcf, vcf_out, include_genotypes, weighting_scheme)
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/lmerge.py", line 524, in r_cluster
[smoove] 2020/02/23 12:37:37 v_id = merge(BP_r, sample_order, v_id, use_product, vcf, vcf_out, include_genotypes, weighting_scheme)
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/lmerge.py", line 493, in merge
[smoove] 2020/02/23 12:37:37 var=create_merged_variant(BP, cliq, v_id, vcf, use_product, weighting_scheme)
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/lmerge.py", line 236, in create_merged_variant
[smoove] 2020/02/23 12:37:37 new_start_L, new_start_R, p_L , p_R, ALG = combine_pdfs(BP, c, use_product, weighting_scheme)
File "/home/u/f056598/miniconda2/lib/python2.7/site-packages/svtools/lmerge.py", line 180, in combine_pdfs
[smoove] 2020/02/23 12:37:37 if (a_L[c_i][pmax_i_L] == 0) or (a_R[c_i][pmax_i_R] == 0):
IndexError: list index out of range
2020/02/23 12:37:37 exit status 1

Thanks a lot for your help! :)

**Comment by brentp** [comment]
you have a truncated input vcf. you'll have to check all 206 files with something like:
```
zcat $vcf | awk 'NF != 10'
```

**Comment by lee039** [comment]
should the truncated file be called again using 'smoove call' ?

**Comment by lee039** [comment]
I am a bit confused, because the merging of 206 samples stopped at chr20:54577355.
but, not with this command:
for vcf in *.vcf.gz
do
	echo $vcf
	zcat $vcf | grep -v '##'  | grep -v 'BND' | awk 'NF != 10' 
done

there are many lines before chr 20...
Am I doing something non-sense?

**Comment by lee039** [comment]
I did this but nothing was returned:
for vcf in *.genotyped.vcf.gz
do
	echo $vcf
	zcat $vcf | grep -v '##'  | awk 'NF != 10' 
done

Also, I was trying merging a subset of 206  samples, trying to figure out a vcf or vcfs that cause the problem. indeed I found two vcfs where merging did not work. These files did not return anything for awk 'NF != 10' either.

Do you have any other clues....?

Thanks a lot in advance.

**Comment by brentp** [comment]
`zgrep -Pv "^#|CIPOS" $vcf` for each vcf. then repeat for CIEND.

**Comment by brentp** [comment]
actually. should grep for absence of PRPOS and PREND not CIPOS and CIEND

**Comment by lee039** [comment]
for CIPOS, CIEND, PRPOS, end PREND, I do not have samples without these tags.

**Comment by brentp** [comment]
well, I'm not sure how to help you. I would ask on the svtools list. It seems the remaining possiblity is that you have a truncated PRPOS or PREND. it seems you found the samples that trigger the error so you could re-run those.

**Comment by lee039** [comment]
I identified two samples so far, that stops the merging process, at the same position.
however, they have PROPOS and PREND tags annotated correctly.

Could what is annotated in these tags causing problems?

**Comment by brentp** [comment]
the tags may be present, but, for example they may have 95 comma-delimited values in the field instead of e.g. 200.

**Comment by lee039** [comment]
hmm. maybe a dumb question. but how does it matter if you have 95 , delimited values, instead of 200?

**Comment by brentp** [comment]
because if svtools is indexing into PRPOS[123] and you only have 95, then you'll get an IndexError, which is the error you have reported.

**Comment by lee039** [comment]
Hi,

I thought I at least was able to identify samples with problem (without knowing what is the problem), but I think I was wrong. I realized that some samples that did not have any problem with merging in a previous merge run with a subset also had a problem merging this time.

I am considering subsetting all the vcf files to remove the problem region, where the merge stops each time. Do you see any problem with this approach?

**Comment by lee039** [comment]
I removed the variants that cause the merging problem. Without the problem variants, merging goes smoothly.
Would you be interested in having a look? I can send you the vcf file, if you are interested.

I checked the problem site in IGV and the variants are occurring at repeat sites, so the CIPOS and CIEND are both very broad. and I am wondering whether it has to do with the error in merging.
