### ISSUE TITLE
Failed to open -: unknown file type panic: exit status 255

### ISSUE THREAD

**Issue by NTNguyen13** [brentp/smoove#110]
Hi, I'm trying Smoove/Lumpy on my sample in Large cohort mode, my command:

```
    docker run -v `pwd`:`pwd` -it brentp/smoove smoove call \
        --exclude $ex_target \
        --outdir /home/nguyen/RB1/Smoove/ \
        --name $sample \
        --fasta $ref_fasta -p 1 --genotype $final_bam
```

in the first half, it runs smoothly to produce and filter discordant and split reads, however, it fails at the genotyping step:
```
[smoove] 2020/04/28 09:39:43 2020/04/28 09:39:43 EOF
[smoove] 2020/04/28 09:39:43 Failed to open -: unknown file type
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
        /home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xbd75a0, 0xc000154568, 0x7ffdc0d3fe68, 0x1b, 0xc0001575e0, 0x1, 0x1, 0x7ffdc0d3fe35, 0x18, 0x7ffdc0d3fe55, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:226 +0x17f8
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:347 +0x44f
main.main()
        /home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce
```

When I run the command with out `exclude` parameter, it runs fine. Because my interesting region is quite small, only a part of chr13, so the ex_target file cover most of the chromosome.

Please guide me on this problem, thank you

**Comment by brentp** [comment]
it must be that when you use the exclude, the result it empty. I should guard against empty file, but haven't added that yet.

**Comment by NTNguyen13** [comment]
thank you for clarification.
