### ISSUE TITLE
Unbound variable SAMPLE when running smoove docker

### ISSUE THREAD

**Issue by tirohia** [brentp/smoove#111]
I have the following docker command:

 ```
docker run -it \
    --mount=type=bind,source=/blue/project/gridssTest/data/bams,target=/data \
    --mount=type=bind,source=/blue/project/cancer-seq-pipeline/data/references/hg19/,target=/reference brentp/smoove \
     smoove call \
    --name trio003 \
    --fasta /reference/ucsc.hg19.fasta 
   /data/trio003_mother.bam
```
which generates the following error:
```
[smoove] 2020/05/13 07:29:23 starting with version 0.2.5
[smoove] 2020/05/13 07:29:23 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2020/05/13 07:29:23 /bin/bash: SAMPLE: unbound variable
[smoove]:2020/05/13 07:29:23 finished process: lumpy-filter (set -eu; lumpy_filter -f /reference/ucsc.hg19.fasta /data/trio003_mother.bam .//$SAMPLE.split.bam.tm) in user-time:0s system-time:8.206ms
[smoove]:2020/05/13 07:29:23 error running command: set -eu; lumpy_filter -f /reference/ucsc.hg19.fasta /data/trio003_mother.bam .//$SAMPLE.split.bam.tmp.bam .//$SAMPLE.disc.bam.tmp.bam 2 && mv .//$SAMPLE.split.bam.tmp.bam .//$SAMPLE.split.bam && mv .//$SAMPLE.disc.bam.tmp.bam .//$SAMPLE.disc.bam && cp .//$SAMPLE.split.bam .//$SAMPLE.split.bam.orig.bam && cp .//$SAMPLE.disc.bam .//$SAMPLE.disc.bam.orig.bam -> exit status 1
[smoove] 2020/05/13 07:29:43 done calculating bam stats
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffdcdaf2ea1, 0x7, 0x7ffdcdaf2eb1, 0x1a, 0xaf76c4, 0x2, 0xc00018e580, 0x1, 0x1, 0xc0000f5cc0, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x57e
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
        /home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce

```

It's looking for a variable called SAMPLE. There's nothing that I can see in the documentation regarding a variable of that name, and indeed when I try and add it in (just to see what happens) it throws an error. 
From the line that prints out the command that it executes, it very much looks like it's used as a placeholder for temporarily generated discordant and split reads file that hasn't been generated at some point?

**Comment by brentp** [comment]
can you report the output of `samtools view -H   /data/trio003_mother.bam` ? There is no use of `$SAMPLE` in smoove, but I'm wondering if your read-group indicates the sample name of (literally) `$SAMPLE`.

**Comment by tirohia** [comment]
That appears to be it. Entertainingly, I tested it on multiple bams before I posted, I appear to have screwed up the read groups for that entire run, I'll fix that and re-run, I'm assuming that will fix it.
