### ISSUE TITLE
smoove failed at lumpy_filter

### ISSUE THREAD

**Issue by biozzq** [brentp/smoove#113]
Dear @brentp 

The BAM file was generated by BWA-MEM (alignment without -M) and picard (remove duplication). When using it to detect CNV using smoove using following command, the program failed at lumpy-filter. I also tried to run lumpy-filter alone, the same error persists. Hope you can give me some suggestion. Thank you. Also, this issue has also been mentioned [before](https://github.com/arq5x/lumpy-sv/issues/335#issuecomment-638278093) .
```
./smoove call --name chicken --fasta /home/test/Gallus_gallus.GRCg6a.dna.chromosome.total.fa --processes 4 --outdir 03DJ13 --genotype --duphold /home/test/03DJ13.sorted.markdup.bam
[smoove] 2020/06/04 08:11:20 starting with version 0.2.5
[smoove] 2020/06/04 08:11:20 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2020/06/04 08:11:21 /bin/bash: line 1: 175548 Segmentation fault      (core dumped) lumpy_filter -f /home/test/Gallus_gallus.GRCg6a.dna.chromosome.total.fa /home/test/03DJ13.sorted.markdup.bam 03DJ13/DJ13.split.bam.tmp.bam 03DJ13/DJ13.disc.bam.tmp.bam 2
[smoove]:2020/06/04 08:11:21 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/test/Gallus_gallus.GRCg6a.dna.chromosome.total.fa /home/test/03DJ13.s) in user-time:2.974ms system-time:18.914ms
[smoove]:2020/06/04 08:11:21 error running command: set -eu; lumpy_filter -f /home/test/Gallus_gallus.GRCg6a.dna.chromosome.total.fa /home/test/03DJ13.sorted.markdup.bam 03DJ13/DJ13.split.bam.tmp.bam 03DJ13/DJ13.disc.bam.tmp.bam 2 && mv 03DJ13/DJ13.split.bam.tmp.bam 03DJ13/DJ13.split.bam && mv 03DJ13/DJ13.disc.bam.tmp.bam 03DJ13/DJ13.disc.bam && cp 03DJ13/DJ13.split.bam 03DJ13/DJ13.split.bam.orig.bam && cp 03DJ13/DJ13.disc.bam 03DJ13/DJ13.disc.bam.orig.bam -> exit status 139
[smoove] 2020/06/04 08:11:31 done calculating bam stats
panic: exit status 139

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7fff536e531c, 0x7, 0x7fff536e532c, 0x37, 0x7fff536e537b, 0x6, 0xc0001a35b0, 0x1, 0x1, 0xc0001ac960, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x57e
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce
```
Sincerely.
Zhuqing

**Comment by brentp** [comment]
OK. So this is a different issue than the one in the lumpy repo? Here, lumpy_filter is segfaulting.
If you run:
```
lumpy_filter -f /home/test/Gallus_gallus.GRCg6a.dna.chromosome.total.fa /home/test/03DJ13.sorted.markdup.bam 03DJ13/DJ13.split.bam.tmp.bam 03DJ13/DJ13.disc.bam.tmp.bam 2
```
and it segfaults, then that would narrow it down. if you can provide the bam file (03DJ13.sorted.markdup.bam ) then it would be possible to debug why this is happening.

**Comment by biozzq** [comment]
Dear @brentp 

Thank you. Yes, lumpy_filter is segfaulting when running alone. Since the BAM file was so large, I only attached a small demo generated by `samtools view -s 0.001`; I also attached the lumpy_filter and the reference genome I used, hope these can help you.
[downsample.zip](https://github.com/brentp/smoove/files/4734624/downsample.zip)
[lumpy_filter.zip](https://github.com/brentp/smoove/files/4734659/lumpy_filter.zip)
the reference file can download from following link:
https://drive.google.com/file/d/1i5Ky_P5e5xWXD68CWawXAANcEwVXygd2/view?usp=sharing

Sincerely,
Zhuqing

**Comment by brentp** [comment]
Thanks, and it does segfault with these subsets?

**Comment by biozzq** [comment]
Dear @brentp 

It also gave me seg fault when using these subsets. However, it's very strange when I migrate these files to another compute node, the lumpy_filter runs smoothly. It's very strange for me as this is first time with such problem. 

Sincerely,
Zhuqing

**Comment by brentp** [comment]
you might make sure you have the most recent lumpy on the machine where you had a problem. Also ensure you have set TMPDIR environment variable to somehwere with sufficient space.

**Comment by biozzq** [comment]
Dear @brentp 

The version of lumpy is V.0.2.13 which was installed using anaconda. I think this version should be the most recent. However, I do not know how to set the TMPDIR when running lumpy_filter or smoove.

Sincerely,
Zhuqing

**Comment by biozzq** [comment]
Dear @brentp 

The smoove ran smoothly after installing lumpy by conda in an online environment. The above error occurred when installing lumpy by conda in an offline environment. I found the main different is the file name of the installed packages in different environments (online: lumpy-sv-0.2.14a and using command `anaconda2/bin/conda install -c bioconda lumpy-sv`; offline: lumpy-sv-0.3.0-h0b85cd1_2.tar.bz2 and using command `anaconda2/bin/conda install --offline lumpy-sv-0.3.0-h0b85cd1_2.tar.bz2`), however, I found the versions of lumpy and lumpy_filter are same (lumpy V.0.2.13). Hopefully this information will help anyone in need.

Sincerely
Zhuqing
