### ISSUE TITLE
excluding variants with all unknown or homozygous reference genotypes

### ISSUE THREAD

**Issue by tyyiyi** [brentp/smoove#118]
Command line:
$smoove call --outdir $smooveout --name ${tumor}_${normal} --fasta $ref -p 1 --genotype $tdata/$tumor.MarkDuplicates.bam $ndata/$normal.MarkDuplicates.bam

error:
[smoove] 2020/07/16 16:40:21 starting with version 0.2.3
[smoove] 2020/07/16 16:40:21 calculating bam stats for 2 bams
[smoove]: ([E]lumpy-filter) 2020/07/16 16:41:40 [lumpy_filter] extracted splits and discordants from 63424
894 total aligned reads
[smoove]:2020/07/16 16:41:41 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/cmding/02_data
base/01_ref_genome/UCSC_hg38.fa /home/cmding/06_tangyin) in user-time:2m11.538315s system-time:18.338641s
[smoove]:([E]lumpy-filter) 2020/07/16 16:42:04 [lumpy_filter] extracted splits and discordants from 559760
05 total aligned reads
[smoove]:2020/07/16 16:42:04 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/cmding/02_data
base/01_ref_genome/UCSC_hg38.fa /home/cmding/06_tangyin) in user-time:48.568677s system-time:5.56409s
[smoove] 2020/07/16 16:45:02 done calculating bam stats
[smoove] 2020/07/16 16:47:49 removed 535150 alignments out of 8461480 (6.32%) with low mapq, depth > 1000,
 or from excluded chroms from 12-0RP.disc.bam in 167 seconds
[smoove] 2020/07/16 16:47:49 removed 101176 alignments out of 8461480 (1.20%) that were bad interchromosom
als or flanked-splitters from 12-0RP.disc.bam
[smoove] 2020/07/16 16:50:21 removed 310346 singletons and isolated interchromosomals of 7825154 reads (3.
97%) from 12-0RP.disc.bam in 152 seconds
[smoove] 2020/07/16 16:50:21 7514808 reads (88.81%) of the original 8461480 remain from 12-0RP.disc.bam
[smoove] 2020/07/16 16:51:28 removed 78302 alignments out of 211441 (37.03%) with low mapq, depth > 1000,
or from excluded chroms from 229N_S1_L002.disc.bam in 50 seconds
[smoove] 2020/07/16 16:51:28 removed 17759 alignments out of 211441 (8.40%) that were bad interchromosomal
s or flanked-splitters from 229N_S1_L002.disc.bam
[smoove] 2020/07/16 16:51:29 removed 96390 singletons and isolated interchromosomals of 115380 reads (83.5
4%) from 229N_S1_L002.disc.bam in 1 seconds
[smoove] 2020/07/16 16:51:29 18990 reads (8.98%) of the original 211441 remain from 229N_S1_L002.disc.bam
[smoove] 2020/07/16 16:52:13 removed 4306 alignments out of 14410 (29.88%) with low mapq, depth > 1000, or
 from excluded chroms from 12-0RP.split.bam in 43 seconds
[smoove] 2020/07/16 16:52:13 removed 3356 alignments out of 14410 (23.29%) that were bad interchromosomals
 or flanked-splitters from 12-0RP.split.bam
[smoove] 2020/07/16 16:52:13 removed 4675 singletons of 6748 reads (69.28%) from 12-0RP.split.bam in 0 sec
onds
[smoove] 2020/07/16 16:52:13 2073 reads (14.39%) of the original 14410 remain from 12-0RP.split.bam
[smoove] 2020/07/16 16:52:59 removed 71577 alignments out of 150480 (47.57%) with low mapq, depth > 1000,
or from excluded chroms from 229N_S1_L002.split.bam in 46 seconds
[smoove] 2020/07/16 16:52:59 removed 21191 alignments out of 150480 (14.08%) that were bad interchromosoma
ls or flanked-splitters from 229N_S1_L002.split.bam
[smoove] 2020/07/16 16:52:59 removed 20439 singletons of 57712 reads (35.42%) from 229N_S1_L002.split.bam
in 1 seconds
[smoove] 2020/07/16 16:52:59 37273 reads (24.77%) of the original 150480 remain from 229N_S1_L002.split.ba
m
[smoove] 2020/07/16 16:53:00 starting lumpy
[smoove] 2020/07/16 16:53:00 wrote lumpy command to /home/cmding/06_tangying/01_SFG_CRC/05_smoove_out/12-0
RP_229N_S1_L002-lumpy-cmd.sh
[smoove] 2020/07/16 16:53:00 writing sorted, indexed file to /home/cmding/06_tangying/01_SFG_CRC/05_smoove
_out/12-0RP_229N_S1_L002-smoove.genotyped.vcf.gz
[smoove] 2020/07/16 16:53:00 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2020/07/16 16:53:00 > gsort version 0.1.4
[smoove] 2020/07/16 16:53:00 chr1       1000000
[smoove] 2020/07/16 16:53:00 Traceback (most recent call last):
  File "/home/cmding/03_software/01_anaconda3/anaconda3/envs/bcftools19/bin/svtyper", line 1806, in <modul
e>
[smoove] 2020/07/16 16:53:00     sys.exit(main())
[smoove] 2020/07/16 16:53:00   File "/home/cmding/03_software/01_anaconda3/anaconda3/envs/bcftools19/bin/svtyper", line 1801, in main
[smoove] 2020/07/16 16:53:00     args.max_reads)
  File "/home/cmding/03_software/01_anaconda3/anaconda3/envs/bcftools19/bin/svtyper", line 1357, in sv_genotype
    bam_list.append(pysam.AlignmentFile(b, mode='rb'))
AttributeError: 'module' object has no attribute 'AlignmentFile'
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xa88960, 0xc00000c1b0, 0x7ffcb3222d81, 0x33, 0xc000150880, 0x2, 0x2, 0x7ffcb3222d2c, 0x31, 0x7ffcb3222d65, ...)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:159 +0x18e5
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:346 +0x468
main.main()
        /home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7
Exception in thread "main" java.lang.RuntimeException: File not found '/home/cmding/06_tangying/01_SFG_CRC/05_smoove_out/12-0RP_229N_S1_L002-smoove.genotyped.vcf.gz'
        at org.snpeff.util.Gpr.reader(Gpr.java:524)
        at org.snpeff.util.Gpr.reader(Gpr.java:507)
        at org.snpeff.fileIterator.MarkerFileIterator.init(MarkerFileIterator.java:63)
        at org.snpeff.fileIterator.FileIterator.<init>(FileIterator.java:39)
        at org.snpeff.fileIterator.MarkerFileIterator.<init>(MarkerFileIterator.java:36)
        at org.snpeff.fileIterator.VcfFileIterator.<init>(VcfFileIterator.java:81)
        at org.snpsift.SnpSift.openVcfInputFile(SnpSift.java:455)
        at org.snpsift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:349)
        at org.snpsift.SnpSiftCmdFilter.run(SnpSiftCmdFilter.java:331)
        at org.snpsift.SnpSift.run(SnpSift.java:588)
        at org.snpsift.SnpSift.main(SnpSift.java:76)

I don't know what's wrong, can you give me some advice.
Thanks.
tang

**Comment by brentp** [comment]
This is the error:
```
File "/home/cmding/03_software/01_anaconda3/anaconda3/envs/bcftools19/bin/svtyper", line 1357, in sv_genotype
bam_list.append(pysam.AlignmentFile(b, mode='rb'))
AttributeError: 'module' object has no attribute 'AlignmentFile'
panic: exit status 1
```
Is your svtyper and pysam installed correctly?

**Comment by tyyiyi** [comment]
Thank you so much. It's a version problem.
