### ISSUE TITLE
svtyper error 

### ISSUE THREAD

**Issue by pauline-ng** [brentp/smoove#119]
Hi,

When running smoove, I get an error with svtyper.

Here's my command:
` docker run  -v /data:/data brentp/smoove smoove call --name NA24385_b38_smoov   --fasta /data/SV/ref_fasta/GRCh38/GRCh38_full_analysis_set_plus_decoy_hla.fa -p 12 --excludechroms '~^GL,~^HLA,~_random,~^chrUn,~alt,~decoy' --genotype /data/SV/NA24385/samblaster_38/na24385.samblaster.sorted.hg38.bam  --outdir /data/SV `

I should note that I'm running build 38, which uses "chr1", "chr2" (has "chr" in front of the string.) Also, I was able to run smoove with a build 37 bam (no "chr" in front).

[smoove] 2020/07/23 02:42:04 20	1000000
[smoove] 2020/07/23 02:42:05 21	1000000
21	2000000
21	4000000
21	8000000
21	16000000
[smoove] 2020/07/23 02:42:05 22	1000000
22	2000000
22	4000000
22
[smoove] 2020/07/23 02:42:05 	8000000
22	16000000
22	32000000
[smoove] 2020/07/23 02:42:05 X	1000000
[smoove] 2020/07/23 02:42:06 Y	1000000
Y	2000000
Y	4000000
[smoove] 2020/07/23 02:51:33 Traceback (most recent call last):
  File "/opt/conda/envs/smoove-env/bin/svtyper", line 11, in <module>
    load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
[smoove] 2020/07/23 02:51:33     sys.exit(main())
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
[smoove] 2020/07/23 02:51:33     args.max_ci_dist)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 281, in sv_genotype
[smoove] 2020/07/23 02:51:33     read_batch, many = gather_all_reads(sample, chromA, posA, ciA, chromB, posB, ciB, z, max_reads)
[smoove] 2020/07/23 02:51:33   File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 57, in gather_all_reads
[smoove] 2020/07/23 02:51:33     read_batch, many = gather_reads(sample, chromA, posA, ciA, z, read_batch, max_reads)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 81, in gather_reads
[smoove] 2020/07/23 02:51:33     min(pos + ci[1] + fetch_flank, chrom_length))):
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
[smoove] 2020/07/23 02:51:33 ValueError: invalid contig `1`
[smoove] 2020/07/23 02:51:33 Traceback (most recent call last):
  File "/opt/conda/envs/smoove-env/bin/svtyper", line 11, in <module>
    load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
[smoove] 2020/07/23 02:51:33     sys.exit(main())
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
[smoove] 2020/07/23 02:51:33     args.max_ci_dist)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 281, in sv_genotype
[smoove] 2020/07/23 02:51:33     read_batch, many = gather_all_reads(sample, chromA, posA, ciA, chromB, posB, ciB, z, max_reads)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 57, in gather_all_reads
    read_batch, many = gather_reads(sample, chromA, posA, ciA, z, read_batch, max_reads)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 81, in gather_reads
    min(pos + ci[1] + fetch_flank, chrom_length))):
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
[smoove] 2020/07/23 02:51:33   File "pysam/libchtslib.pyx", line 686, in pysam.libchtslib.HTSFile.parse_region
[smoove] 2020/07/23 02:51:33 ValueError: invalid contig `4`
panic: exit status 1

goroutine 51094 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper.func2(0xc000c9cae0, 0xc00012d5f0, 0x1, 0x1, 0x7ffc6bf69e03, 0x44, 0xc0024f9aa0, 0x2c, 0xc002cb9fa8, 0xc002cb9fc0, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:179 +0x90b
created by github.com/brentp/smoove/svtyper.Svtyper
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:165 +0xaae

Thanks!
Pauline

**Comment by brentp** [comment]
hi, can you share the bam file? we have run smoove on every single thousand genomes sample (from NYGC) without problem on hg38.

**Comment by junhiuqiu** [comment]
Thank you for your prompt reply,I have 283 samples and my merge sites file have 860875 sites and I run the ulimit -n ,The result is 1024,This may seem normal

**Comment by junhiuqiu** [comment]
Thank you very much! I'll give it a try
