### ISSUE TITLE
panic: exit status 1

### ISSUE THREAD

**Issue by Jersey1234** [brentp/smoove#133]
goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xbd75a0, 0xc00000e110, 0x7ffe7794fd7d, 0x27, 0xc0002895e0, 0x1, 0x1, 0x7ffe7794fd06, 0x22, 0x7ffe7794fd30, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:159 +0x1814
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:347 +0x44f
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce

**Comment by brentp** [comment]
I will need the full command and the full traceback to help you.

**Comment by Jersey1234** [comment]
> 我将需要完整的命令和完整的回溯来帮助您。

i use "smoove call --outdir $result/  --name test --exclude  $exclude  --fasta $fasta -p 1 --genotype $wgs_bwa_samtools_markdup.bam". 
but  some files have some errors  like"
[smoove] 2020/10/10 04:47:03 [W::bcf_hdr_parse] Could not parse header line: #
[E::bcf_hdr_parse] Could not parse the header, sample line not found
[smoove] 2020/10/10 04:47:03 Failed to open -: could not parse header
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xbd75a0, 0xc000278540, 0x7ffe68e02d68, 0x27, 0xc00027b5e0, 0x1, 0x1, 0x7ffe68e02cf1, 0x22, 0x7ffe68e02d1b, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:226 +0x17f8
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:347 +0x44f
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce
(smoove-env) root@bbccfbaa5ae5:/mnt/code/Transfer/T_29990# 
"

**Comment by brentp** [comment]
do all your bams have readgroups? 
or, maybe the bam is so small that you aren't getting any calls in the vcf?

**Comment by lindenb** [comment]
Hi again, I got the same problem  (?) following https://github.com/brentp/smoove/issues/135  (small CRAM files)

```
[smoove] 2020/11/12 16:17:02 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2020/11/12 16:17:02 (..)
[smoove] 2020/11/12 16:17:02 > gsort version 0.0.6
[smoove] 2020/11/12 16:17:04 2020/11/12 16:17:04 EOF
[smoove] 2020/11/12 16:17:04 Failed to read from standard input: unknown file type
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xbd6ec0, 0xc0046fa0c0, 0x7ffc2379ed34, 0x19, 0xc0000f3620, 0x1, 0x1, 0x7ffc2379ecf
9, 0x7, 0x7ffc2379ed24, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:226 +0x17fc
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:347 +0x44f
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce
```

command was: 

```

singularity exec \
	--home ${PWD} 	\
	--bind /sandbox/shares/u1087/lindenb/work/NEXTFLOW/20201112.GRCh37.SCN5A.SMOOVE/work:/xdir \
	--bind /sandbox/shares/u1087/lindenb/work/20201111:/bamdir \
	--bind /sandbox/resources/species/human/cng.fr/hs37d5:/ref \
	--bind ${PWD}/TMP:/outdir \
	smoove.simg \
	smoove call \
	--outdir /outdir \
	--exclude /xdir/exclude.bed \
	--name B00GWGZ 	\
	--fasta /ref/hs37d5_all_chr.fasta \
	-p 1 			--genotype \
	/bamdir/20201111.B00GWGZ.cram
```

```
$ find TMP -type f -name "*.bam" -exec samtools view -c '{}' ';'
20
211
2150
3433
```

**Comment by lindenb** [comment]
ah ok, sorry, it must be that error: https://github.com/brentp/smoove/issues/91#issuecomment-545585184

**Comment by brentp** [comment]
I'll have a look at this. To summarize, the problem seems that smoove can't handle it when a sample has no calls.
