### ISSUE TITLE
panic: read |0: file already closed (+ many small cram files)

### ISSUE THREAD

**Issue by lindenb** [brentp/smoove#135]
Hi @brentp ,

I'm trying to run smoove with a *large* (~1000)  number of *small* (~3M bases) CRAM files. I understand that it is an unusual condition and I might get an error like "too many files open".

I got the following error:

```
(...)
[smoove] 2020/11/12 09:50:30 starting lumpy
[smoove] 2020/11/12 09:50:30 wrote lumpy command to .//prefix-lumpy-cmd.sh
panic: read |0: file already closed

goroutine 560216 [running]:
github.com/brentp/smoove/lumpy.check(...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.bndFilter.func1(0xc0031461f8, 0xc0007248c0, 0xc0009c7ce0, 0xc0021382e8, 0x7ffe496e8a7a, 0x19, 0xc00096b380, 0x6)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:307 +0x7ae
created by github.com/brentp/smoove/lumpy.bndFilter
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:266 +0x29f
(...)
```

with the latest docker, launched with singularity:
```

singularity exec\
        --workdir /sandbox/shares/u1087/lindenb/work/NEXTFLOW/prefix \
        --home /sandbox/shares/u1087/lindenb/work/NEXTFLOW/prefix \
        --bind /sandbox/shares/u1087/lindenb/work/prefix/:/data1 \
        --bind /sandbox/resources/species/human/cng.fr/hs37d5/:/ref \
        --bind /sandbox/shares/u1087/lindenb/work/NEXTFLOW/prefix/:/outdir \
        /sandbox/shares/u1087/lindenb/work/NEXTFLOW/prefix/smoove.simg \
        smoove call -x --name prefix \
        --exclude /outdir/exclude.bed  \
        --fasta /ref/hs37d5_all_chr.fasta \
        --duphold \
        -p 16 --genotype /data1/file1.cram (....)

```

**Comment by brentp** [comment]
Hi Pierre, I'm not sure what's happening there, but with that many samples, I'd follow the instructions for larger cohort calling (even though it's for a small part of the genome)

**Comment by lindenb** [comment]
oh I see now https://github.com/brentp/smoove#population-calling , I was using my 'old' pipeline but I 'll try this !
