### ISSUE TITLE
Error "exit status 83" for lumpy-filter

### ISSUE THREAD

**Issue by clairemerot** [brentp/smoove#137]
Hello, 
I am trying to run Smoove following instructions and really basic paramètres and just one bam file but I am running into an issue at lumpy-filter stage called "exit status 83". Has anyone had this problem (and a solution)? 
Thanks a lot
Claire

 error running command: set -eu; lumpy_filter
[..]
exit status 83
panic: exit status 83

**Comment by brentp** [comment]
Hi, can you make sure you have the latest version of lumpy (and lumpy filter)? I think this was resolved here: https://github.com/arq5x/lumpy-sv/commit/b1b1696e4fd635bc5f3f0da429c9ed6217c65536

**Comment by DavidStreid** [comment]
I am experiencing the same issue w/ v2.7. I have included the error below (editing filenames). Would you be able to help diagnose? Or, point me to where an exit status 83 could be thrown? I don't see mention of it in [filter.c](https://github.com/arq5x/lumpy-sv/blob/master/src/filter/filter.c) so I'm wondering where it could be coming from. Thank you.

```
[smoove] 2022/07/18 14:31:36 starting with version 0.2.7
[smoove] 2022/07/18 14:31:36 calculating bam stats for 1 bams
[smoove] 2022/07/18 14:31:49 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2022/07/18 14:48:10 [lumpy_filter] extracted splits and discordants from 753350339 total aligned reads
[smoove]:2022/07/18 14:48:10 finished process: lumpy-filter (set -eu; lumpy_filter -f hg38.fa) in user-time:39m25.539104s system-time:1m55.014157s		# EDITED REF
[smoove]:2022/07/18 14:48:10 error running command: set -eu; lumpy_filter -f hg38.fa sample.hg38.bam sample.hg38.bam.tmp.bam ...				# EDITED REF/BAM
panic: exit status 83

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffdd48d5317, 0x9, 0x7ffdd48d5394, 0x4b, 0x7ffdd48d5470, 0x3c, 0xc0003997d0, 0x1, 0x1, 0xc0003a2f00, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x57e
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce

```

**Comment by Coaxecva** [comment]
Hi Brent,
I got a similar error message - exit status 127. I tried to build "lumpy_filter" from filter.c, however it didn't work. Can you take a look and see if there's a way to resolve it?

#lumpy_filter
> $ module load htslib/1.9
> 
> The following have been reloaded with a version change:
>   1) htslib/1.5 => htslib/1.9
> 
> $ gcc -Isomehere/include -L/somehere/lib -o lumpy_filter filter.c -lcrypto -lcurl -lpthread -lz -lhts
> filter.c:13:24: fatal error: htslib/sam.h: No such file or directory
>  #include "htslib/sam.h"
>                         ^
> compilation terminated.

#smoove logs
> [smoove] 2022/08/04 22:34:20 starting with version 0.2.8
> [smoove] 2022/08/04 22:34:20 calculating bam stats for 1 bams
> [smoove]: ([E]lumpy-filter) 2022/08/04 22:34:20 /bin/bash: lumpy_filter: command not found
> [smoove]:2022/08/04 22:34:20 finished process: lumpy-filter (set -eu; lumpy_filter -f .../GRCh38_full_analysi) in user-time:2.687ms system-time:3.45ms
> [smoove]:2022/08/04 22:34:20 error running command: set -eu; lumpy_filter -f ....  -> exit status 127
> [smoove] 2022/08/04 22:34:29 done calculating bam stats
> panic: exit status 127
> 
> goroutine 1 [running]:
> github.com/brentp/smoove/lumpy.Lumpy(0x7fffffffba3c, 0xd, 0x7fffffffba52, 0x62, 0x7fffffffb9e9, 0x4b, 0xc0001977e0, 0x1, 0x1, 0xc0001332c0, ...)
> 	/home/brentp/src/smoove/lumpy/lumpy.go:141 +0x587
> github.com/brentp/smoove/lumpy.Main()
> 	/home/brentp/src/smoove/lumpy/lumpy.go:351 +0x29b
> main.main()
> 	/home/brentp/src/smoove/cmd/smoove/smoove.go:121 +0x1c4

Thanks,
Coax

**Comment by brentp** [comment]
The error message is indicating that it didn't find lumpy_filter, so you'd need to update your path.

**Comment by Coaxecva** [comment]
Thanks, Brent. It worked after fixing the path for lumpy_filter, gsort, and bcftools.
