### ISSUE TITLE
smoove failed with "panic: exit status 1"

### ISSUE THREAD

**Issue by HuihuiQ** [brentp/smoove#142]
Hello, everyone! I have some strange error while I run smoove.
At begeinning, I run smoove for a sample and it succeeded. But after that, I run smoove for the rest of samples and it had errors. While I can alse run succeed for that previous sucessful sample. 
The bam files was get from bwa mem, and remove duplicated reads by samtools and GATK (MarkDuplicates).
It confused me deeply. Any helps with most appreciation.

Here is the command what I run:
smoove call --outdir . --name ERR4133368.sort --fasta ../../ARS1/ARS1_2175.fa -p 1 --genotype ERR4133368.markdup_samAndGATK.bam

And here is the error massages:

[smoove] 2021/01/21 16:38:40 starting with version 0.2.6
[smoove] 2021/01/21 16:38:40 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2021/01/21 16:38:40 /bin/bash: a: unbound variable
[smoove]:2021/01/21 16:38:40 finished process: lumpy-filter (set -eu; lumpy_filter -f ../../ARS1/ARS1_2175.fa ERR4133368.markdup_samAndGATK.bam ./${a}.split.bam.) in user-time:0s system-time:3.917ms
[smoove]:2021/01/21 16:38:40 error running command: set -eu; lumpy_filter -f ../../ARS1/ARS1_2175.fa ERR4133368.markdup_samAndGATK.bam ./${a}.split.bam.tmp.bam ./${a}.disc.bam.tmp.bam 2 && mv ./${a}.split.bam.tmp.bam ./${a}.split.bam && mv ./${a}.disc.bam.tmp.bam ./${a}.disc.bam && cp ./${a}.split.bam ./${a}.split.bam.orig.bam && cp ./${a}.disc.bam ./${a}.disc.bam.orig.bam -> exit status 1
[smoove] 2021/01/21 16:38:52 done calculating bam stats
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7fff3079763a, 0xf, 0x7fff30797652, 0x17, 0x7fff30797631, 0x1, 0xc000145600, 0x1, 0x1, 0xc0001012c0, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x57e
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
        /home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce

**Comment by brentp** [comment]
do you have proper read groups in your bam file? I'd clear the directories and start completely over.

**Comment by HuihuiQ** [comment]
I'm very glad to receive your reply.
Yes, I use bwa mem on the Linux (with "for" circulating mapping for some samples), and got read groups like this:
@RG     ID:${a} SM:${a} PL:illumina     LB:${a} PU:${a}
While ${a} is the sample name. And I don't konw why it's ${a} instead of the sample name on the Linux.

For that successful sample, I got read groups like this:
@RG     ID:SRR8354315   SM:SRR8354315   PL:illumina     LB:SRR8354315   PU:SRR8354315

Does "${a}" or "SRR8354315" have deep influence on the downstream analysis (like smoove)? But manta, dally and CNVnator can be run successfully.

Thank you so much!

**Comment by brentp** [comment]
smoove is trying to write a file like `${a}.split.bam` that won't work. 

well, I guess for each sample, you could do:
```
export a=some-unique-name
smoove call ...
```
which might work.

**Comment by HuihuiQ** [comment]
In fact, I have already got split.bam and disc.bam by samblaster when I used bwa mem. And smoove may also create split.bam and disc.bam.

I'll try "a=some-uinque-name".

Thanks!

**Comment by HuihuiQ** [comment]
Wow! While I change "${a}" into the sample unique name in the bam files by "sed" in the Linux, and it can run successfully. 
I don't know why bam files (created by bwa mem in "for" circulation) only have the "${a}" instead of the  sample name. But with your help, I solved my issues.
Thank you very much! Best wishes for you!
