### ISSUE TITLE
smoove failed with "panic: exit status 1",bam.header['RG'][0]['SM'], KeyError: 'RG'

### ISSUE THREAD

**Issue by winternewt** [brentp/smoove#143]
Hello, I run smoove v.0.2.6 within a pipeline https://github.com/antonkulaga/dna-seq, in a container.
To the moment I got two different samples ended up with the same error result. Input bam sequence is assembled by gencore 0.15.0 (https://github.com/OpenGene/gencore)

Any help would be most appreciated.

Here is the call:
`smoove call \
--genotype \
--duphold \
--outdir ./smoove \
--name newtonwinter \
--fasta /cromwell-executions/simple_variant_calling/f07e572a-f716-49bf-880b-f21b1e5e9f3f/call-smoove/inputs/-2130065579/Homo_sapiens.GRCh38.dna.primary_assembly.fa \
/cromwell-executions/simple_variant_calling/f07e572a-f716-49bf-880b-f21b1e5e9f3f/call-smoove/inputs/635203113/newtonwinter.bam`

And below are two results 
`[smoove] 2021/01/21 18:23:01 starting with version 0.2.6
[smoove] 2021/01/21 18:23:01 calculating bam stats for 1 bams
[smoove] 2021/01/21 18:23:06 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2021/01/21 19:42:23 [lumpy_filter] extracted splits and discordants from 791026571 total aligned reads
[smoove]:2021/01/21 19:42:34 finished process: lumpy-filter (set -eu; lumpy_filter -f /cromwell-executions/simple_variant_calling/f07e572a-f716-49bf-880b-f21b1e5) in user-time:7m53.20496s system-time:13m51.817111s
2021/01/21 19:43:04 short read
2021/01/21 19:43:06 short read
[smoove] 2021/01/21 19:43:09 removed 686122 alignments out of 900303 (76.21%) with low mapq, depth > 1000, or from excluded chroms from newtonwinter.split.bam in 35 seconds
[smoove] 2021/01/21 19:43:09 removed 63384 alignments out of 900303 (7.04%) that were bad interchromosomals or flanked-splitters from newtonwinter.split.bam
[smoove] 2021/01/21 19:43:11 kept 1610 putative orphans
[smoove] 2021/01/21 19:43:11 removed 39 split orphans in 1 seconds
[smoove] 2021/01/21 19:43:11 removed 147915 singletons of 150797 reads (98.09%) from newtonwinter.split.bam in 3 seconds
[smoove] 2021/01/21 19:43:11 2882 reads (0.32%) of the original 900303 remain from newtonwinter.split.bam
[smoove] 2021/01/21 19:44:42 removed 6620396 alignments out of 14351288 (46.13%) with low mapq, depth > 1000, or from excluded chroms from newtonwinter.disc.bam in 128 seconds
[smoove] 2021/01/21 19:44:42 removed 95432 alignments out of 14351288 (0.66%) that were bad interchromosomals or flanked-splitters from newtonwinter.disc.bam
[smoove] 2021/01/21 19:45:56 kept 19144 putative orphans
[smoove] 2021/01/21 19:45:56 removed 300382 discordant orphans in 39 seconds
[smoove] 2021/01/21 19:46:31 removed 2183633 singletons and isolated interchromosomals of 7635460 reads (28.60%) from newtonwinter.disc.bam in 109 seconds
[smoove] 2021/01/21 19:46:31 5451827 reads (37.99%) of the original 14351288 remain from newtonwinter.disc.bam
[smoove] 2021/01/21 19:46:33 starting lumpy
[smoove] 2021/01/21 19:46:34 wrote lumpy command to ./smoove/newtonwinter-lumpy-cmd.sh
[smoove] 2021/01/21 19:46:34 writing sorted, indexed file to smoove/newtonwinter-smoove.genotyped.vcf.gz
[smoove] 2021/01/21 19:46:34 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2021/01/21 19:46:36 > gsort version 0.0.6
[smoove] 2021/01/21 19:46:36 684
[smoove] 2021/01/21 19:46:36 	
[smoove] 2021/01/21 19:46:36 0
[smoove] 2021/01/21 19:46:36 
[smoove] 2021/01/21 19:46:36 1
[smoove] 2021/01/21 19:46:36 	
[smoove] 2021/01/21 19:46:36 1000000
[smoove] 2021/01/21 19:46:36 
[smoove] 2021/01/21 19:46:42 Traceback (most recent call last):
[smoove] 2021/01/21 19:46:42   File "/opt/conda/envs/smoove-env/bin/svtyper", line 11, in <module>
    load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
[smoove] 2021/01/21 19:46:42     
[smoove] 2021/01/21 19:46:42 sys.exit(main())
[smoove] 2021/01/21 19:46:42   File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
[smoove] 2021/01/21 19:46:42     
[smoove] 2021/01/21 19:46:42 args.max_ci_dist)
[smoove] 2021/01/21 19:46:42   File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 150, in sv_genotype
[smoove] 2021/01/21 19:46:42     
[smoove] 2021/01/21 19:46:42 sample = Sample.from_bam(bam_list[i], num_samp, min_lib_prevalence)
[smoove] 2021/01/21 19:46:42   File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/parsers.py", line 665, in from_bam
[smoove] 2021/01/21 19:46:42     
[smoove] 2021/01/21 19:46:42 name = bam.header['RG'][0]['SM']
[smoove] 2021/01/21 19:46:42   File "pysam/libcalignmentfile.pyx", line 548, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
[smoove] 2021/01/21 19:46:42 KeyError
[smoove] 2021/01/21 19:46:42 : 
[smoove] 2021/01/21 19:46:42 'RG'
[smoove] 2021/01/21 19:46:42 
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xbd6ec0, 0xc0000ca0b0, 0x7ffcbee8dbe8, 0x9b, 0xc0001a8240, 0x1, 0x1, 0x7ffcbee8dbc3, 0x8, 0x7ffcbee8dbd3, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:159 +0x1818
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:347 +0x44f
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce`

And the same "bam.header['RG'][0]['SM']" issue with the second one at he same processing step:

`[smoove] 2021/01/22 22:24:24 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2021/01/22 22:24:24 716	
[smoove] 2021/01/22 22:24:24 0
[smoove] 2021/01/22 22:24:25 1	1000000
[smoove] 2021/01/22 22:24:25 > gsort version 0.0.6
[smoove] 2021/01/22 22:24:37 Traceback (most recent call last):
[smoove] 2021/01/22 22:24:37   File "/opt/conda/envs/smoove-env/bin/svtyper", line 11, in <module>
    load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
    sys.exit(main())
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
    args.max_ci_dist)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/classic.py", line 150, in sv_genotype
    sample = Sample.from_bam(bam_list[i], num_samp, min_lib_prevalence)
  File "/opt/conda/envs/smoove-env/lib/python2.7/site-packages/svtyper/parsers.py", line 665, in from_bam
    name = bam.header['RG'][0]['SM']
  File "pysam/libcalignmentfile.pyx", line 548, in pysam.libcalignmentfile.AlignmentHeader.__getitem__
KeyError: 'RG'
panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xbd6ec0, 0xc00013c550, 0x7ffc1b6419ee, 0xed, 0xc0001a6240, 0x1, 0x1, 0x7ffc1b6419bd, 0x8, 0x7ffc1b6419cd, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/svtyper/svtyper.go:159 +0x1818
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:347 +0x44f
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce`

**Comment by brentp** [comment]
do your bam/cram files have read-groups?

it could also be that there is no output and so svtyper can't find the read-groups but looks like you might not have read-groups in your bam files.

**Comment by brentp** [comment]
all widely-used aligners will allow you to add read-groups and most downstream tools including smoove require them.

**Comment by 002-two** [comment]
> 

Hello! 
How to read-groups in my bam files?

**Comment by brentp** [comment]
samtools addreplacerg
