### ISSUE TITLE
 error opening fasta file: ref/hg38.fasta: no fai for fasta

### ISSUE THREAD

**Issue by dridk** [brentp/smoove#150]
I ran the following command : 

```
docker run -it -v ${PWD}:/input -v /mnt/R60/bioinformatique/hg38/:/ref brentp/smoove smoove call -x --name test --exclude /ref/exclude.cnvnator_100bp.GRCh38.20170403.bed --fasta ref/hg38.fasta -p 10 --genotype /input/OneSegHumanFemale1.dedup.bam /input/OneSegHumanFemale2.dedup.bam /input/OneSegHumanFemale3.dedup.bam /input/OneSegHumanFemale4.dedup.bam /input/SGT152803pur1.dedup.bam /input/SGT152803pur2.dedup.bam /input/SGT153103nonpur1.dedup.bam /input/SGT153103nonpur2.dedup.bam
```

I get this error : 

```

[smoove] 2021/05/06 16:15:32 starting lumpy
[smoove] 2021/05/06 16:15:32 wrote lumpy command to .//test-lumpy-cmd.sh
[smoove] 2021/05/06 16:15:32 writing sorted, indexed file to test-smoove.genotyped.vcf.gz
[smoove] 2021/05/06 16:15:32 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2021/05/06 16:15:32 > gsort version 0.0.6
[smoove] 2021/05/06 16:15:32 chr1       1000000
panic: error opening fasta file: ref/hg38.fasta: no fai for fasta

goroutine 196547 [running]:
github.com/brentp/smoove/lumpy.check(...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.writeContigs(0xc000147dc0, 0x7ffec56c4db3, 0xe)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:223 +0x558
github.com/brentp/smoove/lumpy.bndFilter.func1(0xc0057462e8, 0xc000147dc0, 0xc00d579500, 0xc008fe3aea, 0x7ffec56c4db3, 0xe, 0xc000db1260, 0x6)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:275 +0x1e9
created by github.com/brentp/smoove/lumpy.bndFilter
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:266 +0x29f
```

But I am sure I have the FAI file  ( generated with samtools faidx ) 

```
(gatk) ➜  output ls /mnt/R60/bioinformatique/hg38/hg38.fasta*
/mnt/R60/bioinformatique/hg38/hg38.fasta      /mnt/R60/bioinformatique/hg38/hg38.fasta.ann  /mnt/R60/bioinformatique/hg38/hg38.fasta.fai  /mnt/R60/bioinformatique/hg38/hg38.fasta.sa
/mnt/R60/bioinformatique/hg38/hg38.fasta.amb  /mnt/R60/bioinformatique/hg38/hg38.fasta.bwt  /mnt/R60/bioinformatique/hg38/hg38.fasta.pac
```

I have no idea... which file name it is looking for ?

**Comment by brentp** [comment]
Error is this: `panic: error opening fasta file: ref/hg38.fasta: no fai for fasta`
you missed the `/` before your ref directory.

**Comment by yqlan** [comment]
> Error is this: `panic: error opening fasta file: ref/hg38.fasta: no fai for fasta` you missed the `/` before your ref directory.

Hi, i have .fai file and i got same error: 

'panic: error opening fasta file: /project2/araman/yqlan/yeastAdaptation_seqData/yeast_reference_genome-genes/sacCer3_WGS_idx/sacCer3.fa: no fai for fasta'



command:
`
genome_idx=/project2/araman/yqlan/yeastAdaptation_seqData/yeast_reference_genome-genes/sacCer3_WGS_idx/sacCer3.fa
smoove_sig=/project2/araman/yqlan/software/smoove.sif
module load singularity/3.4.0
cd /project2/araman/yqlan/yeastAdaptation_seqData/wholeGenomeSeq_results/20240131_LH00315_0080_B22H3W5LT3-AR-Lan-8s

singularity exec $smoove_sig smoove call
--outdir ./smoove_output/
--name AR-Lan-8s
--fasta $genome_idx
--support 100
-p 2
--genotype
./gatk_dataPreprocess/AR-YL-8s-*_recal.bam
`

do you have any suggestions? Thanks.
