### ISSUE TITLE
Specifying multiple BAM files in singularity command

### ISSUE THREAD

**Issue by Phillip-a-richmond** [brentp/smoove#155]
Hey Brent,

Loving smoove for SV calling, and I'm using singularity to work with your docker container (latest as of 2021-06-21). 

The container works great, but when I specify *bam in the singularity command, it throws an error that it can't find the file. Perhaps this is a simple fix but I couldn't find much about using wildcards for files in singularity. 

This works:

```
# Go to the submission directory (where the sbatch was entered)
cd $SLURM_SUBMIT_DIR
WORKING_DIR=/mnt/scratch/Precision/EPGEN/PROCESS/EPGEN029/

## Set working space
mkdir -p $WORKING_DIR
cd $WORKING_DIR

#### GRCh38 #### 
echo "GRCh38 genome"
GENOME=GRCh38
FASTA_DIR=/mnt/common/DATABASES/REFERENCES/GRCh38/GENOME/1000G/
FASTA_FILE=GRCh38_full_analysis_set_plus_decoy_hla.fa

SEQ_TYPE=WGS
BAM_DIR=$WORKING_DIR
FAMILY_ID=EPGEN029
PROBAND_ID=EPGEN029-01
MOTHER_ID=EPGEN029-02
FATHER_ID=EPGEN029-03
PED=$FAMILY_ID.ped

PROBAND_BAM=${PROBAND_ID}_${GENOME}.dupremoved.sorted.bam
FATHER_BAM=${FATHER_ID}_${GENOME}.dupremoved.sorted.bam
MOTHER_BAM=${MOTHER_ID}_${GENOME}.dupremoved.sorted.bam

# Smooooooove 
singularity run \
        -B /usr/lib/locale/:/usr/lib/locale/ \
        -B "${BAM_DIR}":"/bamdir/" \
        -B "${FASTA_DIR}":"/genomedir/" \
        -B "${OUTPUT_DIR}":"/output/" \
        /mnt/common/Precision/Smoove/smoove_latest.sif \
        smoove call \
        --outdir "/output/results-smoove/" \
        -p $NSLOTS \
        -x --name ${FAMILY_ID} \
        --fasta "/genomedir/$FASTA_FILE" \
        --genotype \
        "/bamdir/$PROBAND_BAM" \
        "/bamdir/$MOTHER_BAM" \
        "/bamdir/$FATHER_BAM" \
```

And is blazing fast, love it. 

But this does not work:

```
# Go to the submission directory (where the sbatch was entered)
cd $SLURM_SUBMIT_DIR
WORKING_DIR=/mnt/scratch/Precision/EPGEN/PROCESS/EPGEN029/

## Set working space
mkdir -p $WORKING_DIR
cd $WORKING_DIR

#### GRCh38 #### 
echo "GRCh38 genome"
GENOME=GRCh38
FASTA_DIR=/mnt/common/DATABASES/REFERENCES/GRCh38/GENOME/1000G/
FASTA_FILE=GRCh38_full_analysis_set_plus_decoy_hla.fa

SEQ_TYPE=WGS
BAM_DIR=$WORKING_DIR
FAMILY_ID=EPGEN029
PROBAND_ID=EPGEN029-01
MOTHER_ID=EPGEN029-02
FATHER_ID=EPGEN029-03
PED=$FAMILY_ID.ped

PROBAND_BAM=${PROBAND_ID}_${GENOME}.dupremoved.sorted.bam
FATHER_BAM=${FATHER_ID}_${GENOME}.dupremoved.sorted.bam
MOTHER_BAM=${MOTHER_ID}_${GENOME}.dupremoved.sorted.bam


# Smooooooove 

singularity run \
        -B /usr/lib/locale/:/usr/lib/locale/ \
        -B "${BAM_DIR}":"/bamdir/" \
        -B "${FASTA_DIR}":"/genomedir/" \
        -B "${OUTPUT_DIR}":"/output/" \
        /mnt/common/Precision/Smoove/smoove_latest.sif \
        smoove call \
        --outdir "/output/results-smoove/" \
        -p $NSLOTS \
        -x --name ${FAMILY_ID} \
        --fasta "/genomedir/$FASTA_FILE" \
        --genotype \
        "/bamdir/*.dupremoved.sorted.bam"
```

Error:
```
[smoove] 2021/06/22 16:08:52 starting with version 0.2.6
panic: open /bamdir/*.dupremoved.sorted.bam: no such file or directory

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.check(...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.lumpy_filter_cmd(0x7fffffffacf1, 0x1f, 0x7fffffffac77, 0x17, 0x7fffffffacb0, 0x35, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:83 +0x105b
github.com/brentp/smoove/lumpy.Lumpy(0x7fffffffac9f, 0x8, 0x7fffffffacb0, 0x35, 0x7fffffffac77, 0x17, 0xc00020d600, 0x1, 0x1, 0xc000214aa0, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:119 +0x12b
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce
```

Any tips?

Thanks!
Phil

**Comment by brentp** [comment]
Hi Phil, glad to hear it's working well for you. I'd recommend to run iwth --duphold to get those annotatoins as they really help filter to high-quality calls.

For your question, you can just use:
```
        /bamdir/*.dupremoved.sorted.bam
```
(no quotes) instead of:
```
        "/bamdir/*.dupremoved.sorted.bam"
```

**Comment by Phillip-a-richmond** [comment]
Perfect thanks!

**Comment by Phillip-a-richmond** [comment]
Sorry to bug you again but that didn't work...any other suggestions? 

Do you have an example where the wildcards work within a singularity command? Is there something special about how I bind a path on my server to a path in the container? Remarkably little documentation about using wildcards (*) in accessing files within a bound path. Perhaps I'm not googling the right things...

Thanks,
Phil

**Comment by brentp** [comment]
It's always helpful to see the commadn and the output/error of the command.
But, in this case, I think the solution is to put the command inside a bash script. This ensures that it's the bash inside the singularity container that's doing the glob expansion. so you'd have:

```
smoove call \
        --outdir "/output/results-smoove/" \
        -p $NSLOTS \
        -x --name ${FAMILY_ID} \
        --fasta "/genomedir/$FASTA_FILE" \
        -d \
        --genotype \
        /bamdir/*.dupremoved.sorted.bam
```
inside of `smoove.sh`, then run:
```
singularity run \
        -B /usr/lib/locale/:/usr/lib/locale/ \
        -B "${BAM_DIR}":"/bamdir/" \
        -B "${FASTA_DIR}":"/genomedir/" \
        -B "${OUTPUT_DIR}":"/output/" \
        /mnt/common/Precision/Smoove/smoove_latest.sif \
        bash smoove.sh
```

(note I added -d to the smoove call as the duphold annotations are quite good for filtering).

**Comment by Phillip-a-richmond** [comment]
Bingo! 

For anyone else who runs into this issue:

I'm submitting a job script to the scheduler with variables and calls to singularity. 
```
# Number of threads
NSLOTS=$SLURM_CPUS_PER_TASK

# Go to the submission directory (where the sbatch was entered)
cd $SLURM_SUBMIT_DIR
WORKING_DIR=/mnt/scratch/Public/TESTING/GenomicsPipelineTest/

## Set working space
mkdir -p $WORKING_DIR
cd $WORKING_DIR

#### GRCh38 #### 
echo "GRCh38 genome"
GENOME=GRCh38
FASTA_DIR=/mnt/common/DATABASES/REFERENCES/GRCh38/GENOME/1000G/
FASTA_FILE=GRCh38_full_analysis_set_plus_decoy_hla.fa

SEQ_TYPE=WGS
BAM_DIR=$WORKING_DIR
FAMILY_ID=IBS049
PROBAND_ID=HG01770
MOTHER_ID=HG01771
FATHER_ID=HG01772
PED=$FAMILY_ID.ped

PROBAND_BAM=${PROBAND_ID}_${GENOME}.dupremoved.sorted.bam
FATHER_BAM=${FATHER_ID}_${GENOME}.dupremoved.sorted.bam
MOTHER_BAM=${MOTHER_ID}_${GENOME}.dupremoved.sorted.bam

# Smooooooove 
singularity run \
        -B /usr/lib/locale/:/usr/lib/locale/ \
        -B ${BAM_DIR}:/bamdir \
        -B ${FASTA_DIR}:/genomedir \
        -B ${OUTPUT_DIR}:/output \
        /mnt/common/Precision/Smoove/smoove_latest.sif \
        bash /bamdir/smoove.sh $NSLOTS $FAMILY_ID $FASTA_FILE
```

In the singularity call, for Smoove to run on multiple BAMs, it has to be able to evaluate the glob expansion, which it doesn't seem like singularity has the capacity to do that. So, as Brent suggests, I instead use the container to call a simple bash script, passing my variables to the Smoove call along the way:

```
        bash /bamdir/smoove.sh $NSLOTS $FAMILY_ID $FASTA_FILE
```
where the threads (NSLOTS), family ID, and fasta file are passed to the script. 
```
smoove call \
        --outdir "/output/results-smoove/" \
        -p $1 \
        --duphold \
        -x --name $2 \
        --fasta "/genomedir/$3" \
        --genotype \
        /bamdir/*.dupremoved.sorted.bam
```

The inception of glob evaluation in bash scripts. 

Kudos to Brent!
