### ISSUE TITLE
lumpy executable not found in PATH ?

### ISSUE THREAD

**Issue by Navin-techi** [brentp/smoove#160]
hi @brentp tried recompiling the Smoove package with all the dependency found these issues and help on this would be great
```

smoove version: 0.2.7

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools
 *[Y] svtyper
 *[Y] mosdepth [extra filtering of split and discordant files for better scaling]

  [Y] duphold [(optional) annotate calls with depth changes]
  [Y] svtools [only needed for large cohorts].

Available sub-commands are below. Each can be run with -h for additional help.

call        : call lumpy (and optionally svtyper)
merge       : merge and sort (using svtools) calls from multiple samples
genotype    : parallelize svtyper on an input VCF
paste       : square final calls from multiple samples (each with same number of variants)
plot-counts : plot counts of split, discordant reads before, after smoove filtering
annotate    : annotate a VCF with gene and quality of SV call
hipstr      : run hipSTR in parallel
duphold     : run duphold in parallel (this can be done by adding a flag to call or genotype)

```
Even though the package is available while running the below code in gnu parallel I find this error -
`echo 004_F1.cram | parallel -j 2 -S node28 smoove call --outdir /gpfs/data/user/n_smoove/output --exclude /gpfs/data/user/n_smoove/exclude_reg/exclude.cnvnator_100bp.GRCh38.20170403.bed --name 004_F1.cram --fasta /gpfs/data/user/n_smoove/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa -p 1 --genotype 004_F1.cram
`
**[smoove] 2021/07/07 13:41:13 starting with version 0.1.9
[smoove] 2021/07/07 13:41:13 lumpy executable not found in PATH**

**Comment by brentp** [comment]
is your $PATH exported?
just add `export PATH` in the shell before you run the parallel command.

**Comment by brentp** [comment]
... and if it's executing on another node, as it appears, then you'll need to have that path set in the environment where smoove is running.

**Comment by Navin-techi** [comment]
hi @brentp 

Any ideas on why this setup is falling 

`[smoove]: ([E]lumpy-filter) 2021/07/07 15:35:19 [lumpy_filter] extracted splits and discordants from 723768160 total aligned reads
[smoove]:2021/07/07 15:35:19 finished process: lumpy-filter (set -eu; lumpy_filter -f /gpfs/data/user/n_smoove/ref-gen/GRCh38_full_analysis_set_plus_d) in user-time:27m23.731005s system-time:29.125144s
[smoove]:2021/07/07 15:35:19 error running command: set -eu; lumpy_filter -f /gpfs/data/user/n_smoove/ref-gen/GRCh38_full_analysis_set_plus_decoy_hla.fa /gpfs/data/user/n_smoove/cram/001MS.cram /gpfs/data/user/n_smoove/output/001MS.split.bam.tmp.bam /gpfs/data/user/n_smoove/output/001MS.disc.bam.tmp.bam 2 && mv /gpfs/data/user/n_smoove/output/001MS.split.bam.tmp.bam /gpfs/data/user/na_smoove/output/001MS.split.bam && mv /gpfs/data/user/n_smoove/output/001MS.disc.bam.tmp.bam /gpfs/data/user/n_smoove/output/001MS.disc.bam && cp /gpfs/data/user/n_smoove/output/001MS.split.bam /gpfs/data/user/n_smoove/output/001MS.split.bam.orig.bam && cp /gpfs/data/user/n_smoove/output/001MS.disc.bam /gpfs/data/user/n_smoove/output/001MS.disc.bam.orig.bam -> exit status 83
**_panic: exit status 83

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7fffda461a2b, 0x5, 0x7fffda461a39, 0x56, 0x7fffda461994, 0x2a, 0xc0001d37d0, 0x1, 0x1, 0xc00014b360, ...)
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x57e
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
	/home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce_**
`

**Comment by brentp** [comment]
make sure you have the most recent version of lumpy_filter.

**Comment by Navin-techi** [comment]
Using the latest version of lumpy-SV from GitHub ..yet the same problem.

**Comment by brentp** [comment]
I suspect you're still getting the old version of lumpy_filter. if not, try running the lumpy-cmd.sh directly and verify all paths and output.

**Comment by Navin-techi** [comment]
hi @brentp ,
Just a small doubt in the following run which I do use this smoove module is that when at 4th point

**[ paste all the single sample VCFs with the same number of variants to get a single, ]** 


why are find the same number of variants count in all the samples? Secondly, I would like to know how to filter the pass variants for the next level of analysis?

**Comment by brentp** [comment]
let's say that you call variants in a trio. And you call each sample separately. If you find an SV in the kid that's not in the parents, you have know way of knowing if it was actually present in the parents, but below some threshold, or if it was completely absent.

The genotyping, followed by squaring takes every SV and looks for evidence in every sample so we can avoid this ambiguity.
