### ISSUE TITLE
unknown chromosome, Could not parse the header, sample line not found

### ISSUE THREAD

**Issue by mdozmorov** [brentp/smoove#179]
Hi Brent,
I've successfully run smoove on a subset of my data (chr22). When running on the full genome, it fails at the last step of VCF creation. Below are the most informative parts of the error messages. The "unknown chromosome: chrUn_gl000232" is present in the BAM headers. 
```
[smoove] 2021/11/11 15:37:32 starting lumpy
[smoove] 2021/11/11 15:37:32 wrote lumpy command to results-smoove_WGS//UCD52-lumpy-cmd.sh
[smoove] 2021/11/11 15:37:32 writing sorted, indexed file to results-smoove_WGS/UCD52-smoove.genotyped.vcf.gz
[smoove] 2021/11/11 15:37:32 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2021/11/11 15:37:32 > gsort version 0.1.4
[smoove] 2021/11/11 15:37:32 chrM	1000000
[smoove] 2021/11/11 15:37:33 chr1	1000000
...
[smoove] 2021/11/11 15:52:37 chrUn_gl000243	1000000
[smoove] 2021/11/11 15:52:37 chrUn_gl000247	1000000
[smoove] 2021/11/11 15:58:00 2021/11/11 15:58:00 unknown chromosome: chrUn_gl000232 (known: map[chr1:0 chr10:9 chr11:10 chr12:11 chr13:12 chr14:13 chr15:14 chr16:15 chr17:16 chr18:17 chr19:18 chr2:1 chr20:19 chr21:20 chr22:21 chr3:2 chr4:3 chr5:4 chr6:5 chr7:6 chr8:7 chr9:8 chrM:24 chrX:22 chrY:23]) in line: chrUn_gl000232	20413	4364_2	N	N[chr3:197859051[	0.00	.	SVTYPE=BND;...
[smoove] 2021/11/11 15:58:00 [E::bcf_hdr_parse] Could not parse the header, sample line not found
[smoove] 2021/11/11 15:58:00 
[smoove] 2021/11/11 15:58:00 Failed to open -: could not parse header
[smoove] 2021/11/11 15:58:00 Failed to open -: unknown file type
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/src/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xc14cc0, 0xc006f5c0f0, 0x7ffd84f02203, 0x2f, 0xc0001122c0, 0x2, 0x2, 0x7ffd84f022c0, 0x13, 0x7ffd84f021c3, ...)
	/home/brentp/src/smoove/svtyper/svtyper.go:226 +0x190a
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/src/smoove/lumpy/lumpy.go:363 +0x4ab
main.main()
	/home/brentp/src/smoove/cmd/smoove/smoove.go:121 +0x1c4
```
I cannot seem to find issues similar to this. What to do?
Thanks,
Mikhail

**Comment by brentp** [comment]
This likely means that you're using a different fasta file for smoove than you did to align the bam file. Make sure you send smoove a fasta file that includes that `chrUn_gl000232` contig (and all the contigs in the bam header).

**Comment by mdozmorov** [comment]
This is likely the case - the BAM files were produced by a provider and I'm supplying my own FASTA. It is hard to figure out from their BAM header where they got their reference. Thanks so much, I'll realign the data, it should fix the issue.
