### ISSUE TITLE
smoove exits with panic: exit status 1

### ISSUE THREAD

**Issue by am8265** [brentp/smoove#181]
Hello @brentp, 

I ran smoove like this ---

`smoove call --name ${sample} -x --exclude ${blist_region} --fasta ${FASTA} -p 3 --outdir ${sample}_smoove --genotype ${bam_path} `

and the following logs were generated while running:
                    
```
[smoove] 2021/12/28 07:01:59 starting with version 0.2.8
[smoove] 2021/12/28 07:01:59 calculating bam stats for 1 bams
[smoove] 2021/12/28 07:02:08 done calculating bam stats
[smoove]: ([E]lumpy-filter) 2021/12/28 07:18:36 [lumpy_filter] extracted splits and discordants from 998304035 total aligned reads
[smoove]:2021/12/28 07:19:13 finished process: lumpy-filter (set -eu; lumpy_filter -f /nfs/goldsteindata/refDB/HS_Build37/BWA_INDEX_hs37d5/hs37d5.fa /nfs/archive) in user-time:36m28.463383s system-time:2m31.014701s
could not load: libhts.so
compile with -d:nimDebugDlOpen for more information
panic: exit status 1

goroutine 24612 [running]:
github.com/brentp/smoove/lumpy.check(...)
        /home/brentp/src/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.remove_sketchy(0xc0000224e0, 0x27, 0x3e8, 0x7fff26af12bf, 0x3e, 0x7fff26af126c, 0x4a, 0xc000188480, 0x4, 0x4, ...)
        /home/brentp/src/smoove/lumpy/depthfilter.go:232 +0x1825
github.com/brentp/smoove/lumpy.remove_sketchy_all.func1(0xc0000daa80, 0x3e8, 0x7fff26af12bf, 0x3e, 0x7fff26af126c, 0x4a, 0xc000188480, 0x4, 0x4, 0x1, ...)
        /home/brentp/src/smoove/lumpy/depthfilter.go:399 +0x231
created by github.com/brentp/smoove/lumpy.remove_sketchy_all
        /home/brentp/src/smoove/lumpy/depthfilter.go:397 +0x194
(base) dev1:LUMPY$ could not load: libhts.so
compile with -d:nimDebugDlOpen for more information
```

Would really appreciate resolution to this issue and please let me know if you need more information.

Note:
smoove generated these files successfully -- ${sample}.histo, ${sample}.disc.bam, ${sample}.split.bam (and *.split.bam.orig.bam and *disc.bam.orig.bam).

Thanks !

**Comment by brentp** [comment]
Hi, as you can see from the message, `lumpy` is not able to run because it is not able to find libhts.so. So this is a problem with your installation. How did you install smoove and associated dependencies?
