### ISSUE TITLE
smoove annotation

### ISSUE THREAD

**Issue by Johnsonzcode** [brentp/smoove#185]
Hi, @brentp, @lindenb 

Thanks for your great work !
There was a problem with the annotation
```
smoove annotate --gff silkie_end.gff3.gz 26indiv_ZW-smoove.genotyped.vcf.gz | bgzip -c > 26indiv_ZW-smoove.genotyped.anno.vcf.gz

(smoove) [poultrylab1@pbsnode01 sk_as_ref_118_indev_bam]$ sh docker_smoove.sh
[smoove] 2022/01/20 11:23:25 starting with version 0.2.8
panic: runtime error: index out of range [2] with length 1

goroutine 1 [running]:
github.com/brentp/smoove/annotate.passOne(0x7fff46237edb, 0x12, 0xc00026fdc8, 0x1, 0x1, 0xc0003b2160)
        /home/brentp/src/smoove/annotate/annotate.go:156 +0x52f
github.com/brentp/smoove/annotate.readGff(0x7fff46237edb, 0x12, 0x1)
        /home/brentp/src/smoove/annotate/annotate.go:185 +0xc5
github.com/brentp/smoove/annotate.Main()
        /home/brentp/src/smoove/annotate/annotate.go:449 +0xa8
main.main()
        /home/brentp/src/smoove/cmd/smoove/smoove.go:121 +0x1c4

```

I don't know what happen.
Appreciate it !

**Comment by brentp** [comment]
This means that you have a line in your gff that does not start with '#' and has fewer than 2 tab-delimited columns. smoove is not expecting that.

**Comment by Johnsonzcode** [comment]
Thanks, it works. 
By the way.
How I calculate the mutation effect from the output with `smoove annotate` ?

**Comment by brentp** [comment]
Great!
You mean like frameshift or something? smoove does not report that.
