### ISSUE TITLE
Smoove Call panic exit segmentation violation followed by unknown file type 

### ISSUE THREAD

**Issue by mrburke00** [brentp/smoove#199]
```     
        smoove call --genotype \
                    --duphold \
                    --processes 1 \
                    --fasta ref.fa \
                    --exclude ERR4083547.exclude.bed \
                    --name ERR4083547 \
                    --outdir ERR4083547 \
                    ERR4083547.sorted.bam
```
```
[smoove] 2022/06/20 13:19:48 > gsort version 0.1.4
[smoove] 2022/06/20 13:19:48 295	
[smoove] 2022/06/20 13:19:48 0
[smoove] 2022/06/20 13:19:59 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x546d43]

goroutine 1 [running]:
[smoove] 2022/06/20 13:19:59 bufio.NewReaderSize(...)
	/home/brentp/go/src/bufio/bufio.go:49
bufio.NewReader(...)
	/home/brentp/go/src/bufio/bufio.go:62
github.com/brentp/gsort.Sort(0x7ad380, 0x0, 0x7ad3a0, 0xc00038cf00, 0xc00038cec0, 0xaf0, 0x0, 0x0, 0x0)
	/home/brentp/go/go/src/github.com/brentp/gsort/gsort.go:116 +0x63
main.main()
	/home/brentp/go/go/src/github.com/brentp/gsort/cmd/gsort/gsort.go:373 +0x513
[smoove] 2022/06/20 13:19:59 Failed to open -: unknown file type
panic: exit status 255
```

Im getting a exit code I have not yet to come across using Smoove.  It appears that Im getting a simultaneous seg fault and unknown file type error. Its unclear which error is triggering the other. The bam and fa file look to be in working order.

**Comment by brentp** [comment]
Hi, it could be that you are running out of memory, could you give it more memory (and plenty of temp space) and retry?

**Comment by mrburke00** [comment]
It appears this issue was caused by using a reference that had only contig level representation.  I am currently running a test using a reference with chromosome level representation that appears to have successfully passed this step in my pipeline.
