### ISSUE TITLE
panic: open /path/to/*.bam: no such file or directory

### ISSUE THREAD

**Issue by Gummy89** [brentp/smoove#218]
Hi, 

I try to use docker to run smoove, but I meet a problem on smoove call.
I do have my bam file in that directory, and I checked that the paths and names are correct, so I don't know how to fix this.

Below is the command I use.
`docker run -it brentp/smoove smoove call -x --support 3 --duphold --genotype -p 40 \
--name AS_01 \
--outdir /home/data2/TVGH_project/ASC_WES/Welgene/NGS1110946/AS_01/smoove/ \
--fasta /home/data/data_thousand/gatk_index/Homo_sapiens_assembly38.fasta \
/home/data2/TVGH_project/ASC_WES/Welgene/NGS1110946/AS_01/AS_01T_sorted_du_bqsr.bam`

And this is the error message I get.
`[smoove] 2023/05/16 08:10:13 starting with version 0.2.6
panic: open /home/data2/TVGH_project/ASC_WES/Welgene/NGS1110946/AS_01/AS_01T_sorted_du_bqsr.bam: no such file or directory

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.check(...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.lumpy_filter_cmd(0x7ffee0ec6e91, 0x53, 0x7ffee0ec6e05, 0x41, 0x7ffee0ec6e4f, 0x41, 0x0, 0x0, 0x0, 0x0, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:83 +0x105b
github.com/brentp/smoove/lumpy.Lumpy(0x7ffee0ec6df6, 0x5, 0x7ffee0ec6e4f, 0x41, 0x7ffee0ec6e05, 0x41, 0xc000173610, 0x1, 0x1, 0xc0001a6960, ...)
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:119 +0x12b
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/go/src/github.com/brentp/smoove/lumpy/lumpy.go:335 +0x261
main.main()
        /home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:121 +0x1ce`

Thank you!

**Comment by Gummy89** [comment]
I saw the same problem before and solved it.
