### ISSUE TITLE
【need help】

### ISSUE THREAD

**Issue by SolarQuiltc** [brentp/smoove#221]
Hi Brentp,An error occurred while I was running this step

#smoove merge --name merged -f $reference_fasta --outdir ./ results-smoove/*.genotyped.vcf.gz

I ran the program in the format provided by README.md ,But the program exited
smoove merge --name merged --fasta ./ARS-UCD1.2_Btau5.0.1Y.fa --outdir outdir/ ./*genotyped.vcf.gz

[smoove] 2023/07/13 18:57:24 starting with version 0.2.8
[smoove] 2023/07/13 18:57:24 merging 3 files
[smoove] 2023/07/13 18:57:24 finished sorting 3 files; merge starting.
2023/07/13 18:57:24 exit status 1

Generated a file named “merged.lsort.vcf” , The content is as follows:

Traceback (most recent call last):
  File "/home/miniconda3/envs/smoove/bin/lsort", line 70, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/smoove/bin/lsort", line 27, in main
    samples = l_bp.parse_vcf(vcf_file_name, vcf_lines, vcf_headers)
  File "/home/miniconda3/envs/smoove/bin/l_bp.py", line 16, in parse_vcf
    f = open(vcf_file_name, 'r')
IOError: [Errno 2] No such file or directory: '-r'

I tried to modify “l_bp.py” script did not solve the problem

Is it possible that the format of the command I entered was incorrect, which caused me to be unable to read the file correctly？

**Comment by zhachengwan** [comment]
Have you solved it? I have encountered the same problem. Could you please provide some help? Thank you.

**Comment by SolarQuiltc** [comment]
> Have you solved it? I have encountered the same problem. Could you please provide some help? Thank you.
Yes, I solved this problem. I wrote the new version of svtools into the current environment and then ran through this program
