### ISSUE TITLE
smoove call fails immediately with Panic: unexpected EOF

### ISSUE THREAD

**Issue by Ax3man** [brentp/smoove#222]
I am trying to get smoove to run on some guppy sequences. However, it always fails immediately, and it is not clear where to even begin debugging.

I run: 

```
smoove call \
        --outdir lumpy/results_smoove \
        --name test \
        --excludechroms NC_024342.1,~NW \
        --fasta reference/GCF_000633615.1/GCF_000633615.1_Guppy_female_1.0_MT_genomic.fna \
        -p 1 \
        --genotype \
        bam_dedup_test/test.bam
```

It always fails with this error:

```
[smoove] 2023/07/14 14:42:44 starting with version 0.2.8
[smoove] 2023/07/14 14:42:44 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2023/07/14 14:42:44 set: Variable name must begin with a letter.
panic: unexpected EOF

goroutine 16 [running]:
github.com/brentp/goleft/covstats.pcheck(...)
	/home/brentp/go/go/pkg/mod/github.com/brentp/goleft@v0.2.5/covstats/covstats.go:30
github.com/brentp/goleft/covstats.BamStats(0xc000176c00, 0x1312d0, 0x186a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/go/pkg/mod/github.com/brentp/goleft@v0.2.5/covstats/covstats.go:143 +0xcdd
github.com/brentp/smoove/lumpy.bam_stats.func1(0x1)
	/home/brentp/src/smoove/lumpy/lumpy.go:218 +0x209
created by github.com/brentp/smoove/lumpy.bam_stats
	/home/brentp/src/smoove/lumpy/lumpy.go:232 +0x19d
```

Frustratingly, whenever it errors it also overwrites my .bam file with a 0 byte file.

Running e.g. `samtools quickcheck bam_dedup_test/test.bam` indicates no issues. Any idea what could be going on?

Thanks so much!

**Comment by brentp** [comment]
Hi, try a --name other than `test`.
But I don't think lumpy or smoove will work with long-read sequences, it's mostly expecting paired end reads.

**Comment by Ax3man** [comment]
Thanks, I tried a few other names with the same results.

I indeed have 150bp paired-end reads.
