### ISSUE TITLE
Failed to open -: unknown file type, panic

### ISSUE THREAD

**Issue by lilymaya** [brentp/smoove#233]
Hi @brentp,

I am getting the a strange error when I try to run smoove call:

[smoove] 2023/11/03 15:37:14 starting with version 0.1.9
[smoove] 2023/11/03 15:37:14 calculating bam stats for 1 bams
[smoove] 2023/11/03 15:37:16 done calculating bam stats
[smoove]: 2023/11/03 15:48:09 finished process: lumpy-filter (lumpy_filter -f Oed.genome.c) in user-time:1m31.88s system-time:12.34s
[smoove] 2023/11/03 15:48:10 removed 0 alignments out of 0 (NaN%) with depth > 800 or from excluded chroms from BZH_04.disc.bam in 0 seconds
[smoove] 2023/11/03 15:48:10 removed 0 alignments out of 0 (NaN%) that were bad interchromosomals or flanked-splitters from BZH_04.disc.bam
[smoove] 2023/11/03 15:48:10 removed 0 singletons out of 0 reads (NaN%) from BZH_04.disc.bam in 0 seconds
[smoove] 2023/11/03 15:48:10 removed 0 alignments out of 0 (NaN%) with depth > 800 or from excluded chroms from BZH_04.split.bam in 0 seconds
[smoove] 2023/11/03 15:48:10 removed 0 alignments out of 0 (NaN%) that were bad interchromosomals or flanked-splitters from BZH_04.split.bam
[smoove] 2023/11/03 15:48:10 removed 0 singletons out of 0 reads (NaN%) from BZH_04.split.bam in 0 seconds
[smoove] 2023/11/03 15:48:10 starting lumpy
[smoove] 2023/11/03 15:48:10 wrote lumpy command to /home1/svcalling/lumpy/results-smoove/BZH_04-lumpy-cmd.sh
[smoove] 2023/11/03 15:48:10 writing sorted, indexed file to /home1/svcalling/lumpy/results-smoove/BZH_04-smoove.genotyped.vcf.gz
[smoove] 2023/11/03 15:48:10 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2023/11/03 15:48:10 > gsort version 0.0.6
[smoove] 2023/11/03 15:48:11 Calculating library metrics from /BZH_04_SS.bam...
[smoove] 2023/11/03 15:48:15  done
[smoove] 2023/11/03 15:48:15 Writing library metrics to /dev/shm/pbs.7263022[3].datarmor0/tempclean-988305349/086946291svtype-lib...
[smoove] 2023/11/03 15:48:15  done
[smoove] 2023/11/03 15:48:15 2023/11/03 15:48:15 EOF
[smoove] 2023/11/03 15:48:15 Failed to open -: unknown file type
[smoove] 2023/11/03 15:48:15 wrote sorted, indexed file to /home1/svcalling/lumpy/results-smoove/BZH_04-smoove.genotyped.vcf.gz
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(0x9f3060, 0xc420282920)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:32 +0x4a
github.com/brentp/smoove/svtyper.Svtyper(0x9f2b80, 0xc42000c110, 0x7fffffffe017, 0x5c, 0xc4200b5280, 0x1, 0x1, 0x7fffffffdfbe, 0x42, 0x7fffffffe008, ...)
        /home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:215 +0xbee
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:287 +0x3fb
main.main()
        /home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:115 +0x1dd

This error pops up for every individual file that I have. I have been scouring the Issues tab but I haven't found anything that matches this problem.

Do you have any suggestions? Thank you so much in advance!

**Comment by brentp** [comment]
You file doesn't appear to have any split or discordant reads. Was it aligned with bwa mem? Is it paired end?

**Comment by lilymaya** [comment]
Yes and yes! Oops, is this an issue I have missed somewhere?

**Comment by lilymaya** [comment]
Hi @brentp, I have looked through the issues and I haven't been able to find a definitive answer, but from what I understand, I can align with BWA MEM but perhaps I shouldn't then filter these reads? Could you please confirm how to prep the input files? Thank you so much!

**Comment by brentp** [comment]
Align with bwa mem, mark duplicates, sort and index. Then send to smoove without filtering.
They should be paired end reads.

**Comment by lilymaya** [comment]
Great, thank you so much for your help and quick reply! :)
