### ISSUE TITLE
issue with installation smoove via conda

### ISSUE THREAD

**Issue by Ana1335** [brentp/smoove#236]
Hi Brent,
I am reaching out regarding the smoove installation via conda.
It seems a very fantastic tool but I am having a very tough time installing it. It keeps complaining about lumpy-filter which seems to be related to samtools. I also tried to install samtools separately but it does not work.
Is there any updated conda version that can help with the successful installation?
I have seen some other people have had the same issue.
I really appreciate your help on this matter, so we can using this awesome tool. Thanks a lot

**Comment by Ana1335** [comment]
Hi Brent. Thanks so much for your prompt reply.
I have tried several times with fresh environments installing lumpy-sv followed by smoove and vise versa. Already removed all of those environment.
the current error :

```
conda install -c bioconda smoove
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): / Killed

```

Do you happen to have a yaml file to share? that make work out

**Comment by Ana1335** [comment]
```
Current working directory: /oak/stanford/groups/emoding/analysis/shaghayegh/scripts/SR-scripts
Starting run at: Mon Dec 11 16:14:12 PST 2023

Job Array ID / Job ID: 37655100 / 37655100
This is job 1 out of 1 jobs.

[smoove] 2023/12/11 16:14:15 starting with version 0.2.8
[smoove] 2023/12/11 16:14:15 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2023/12/11 16:14:15 lumpy_filter: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
[smoove]:2023/12/11 16:14:15 finished process: lumpy-filter (set -eu; lumpy_filter -f /oak/stanford/groups/emoding/sequencing/pipeline/indices/hg19.fa /oak/stanf) in user-time:0s system-time:3.416ms
[smoove]:2023/12/11 16:14:15 error running command: set -eu; lumpy_filter -f /oak/stanford/groups/emoding/sequencing/pipeline/indices/hg19.fa /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/alignment-BWA/dedupped_BAMs_picard/GCT.rmdup1.bam /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.split.bam.tmp.bam /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.disc.bam.tmp.bam 2 && mv /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.split.bam.tmp.bam /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.split.bam && mv /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.disc.bam.tmp.bam /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.disc.bam && cp /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.split.bam /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.split.bam.orig.bam && cp /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.disc.bam /oak/stanford/groups/emoding/analysis/shaghayegh/shortreads-SV/results-smoove/GCT-rmdup1.disc.bam.orig.bam -> exit status 127
[smoove] 2023/12/11 16:14:24 done calculating bam stats
panic: exit status 127

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffd449ae2e7, 0x3, 0x7ffd449ae2f3, 0x40, 0x7ffd449ae21f, 0x4d, 0xc0001277f0, 0x1, 0x1, 0xc0000c3040, ...)
	/home/brentp/src/smoove/lumpy/lumpy.go:141 +0x587
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/src/smoove/lumpy/lumpy.go:351 +0x29b
main.main()
	/home/brentp/src/smoove/cmd/smoove/smoove.go:121 +0x1c4
Job finished with exit code 2 at: Mon Dec 11 16:14:24 PST 2023

```

This is also one error when I was still able to install loopy and smoove on my conda. but as I said I removed that environment to install a fresh one and now even fail to install them

**Comment by Ana1335** [comment]
Hey just wanted to let you know I fixed the library error. I was installing lumpy and then smoove through conda but it seems installing lumpy is causing some conflicts. I just installed smoove and obviously it is working now. closing the issue
