### ISSUE TITLE
Smoove filters out almost all reads when using BAMs of a 1.5 Mb region of the genome 

### ISSUE THREAD

**Issue by Alexei-Lipov** [brentp/smoove#248]
Hi,

My understanding is that the error below is caused by only having 22 reads after smoove filtering (starting with 1349 reads). I am trying to call SVs using BAMs which correspond to a 1.5 Mb region of the genome. Is it still possible to use smoove with these size BAMs? Is there a way to reduce the stringency of the filtering process?

Many thanks,

Alex

```
[smoove] 2024/07/28 23:07:20 starting with version 0.2.8
[smoove] 2024/07/28 23:07:20 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2024/07/28 23:07:21 [lumpy_filter] extracted splits and discordants from 394784 total aligned reads
[smoove]:2024/07/28 23:07:21 finished process: lumpy-filter (set -eu; lumpy_filter -f /projects/0/brugada/Realingment/brugada-realign/reference/hs37d5_all_chr.fa) in user-time:432.07
2ms system-time:134.567ms
[smoove] 2024/07/28 23:07:21 done calculating bam stats
[smoove] 2024/07/28 23:07:22 removed 859 alignments out of 1869 (45.96%) with low mapq, depth > 1000, or from excluded chroms from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-
hs37d5-D000Q53-FRENCHWGGAZEL.disc.bam in 2 seconds
[smoove] 2024/07/28 23:07:22 removed 169 alignments out of 1869 (9.04%) that were bad interchromosomals or flanked-splitters from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-h
s37d5-D000Q53-FRENCHWGGAZEL.disc.bam
[smoove] 2024/07/28 23:07:22 kept 2 putative orphans
[smoove] 2024/07/28 23:07:22 removed 4 discordant orphans in 0 seconds
[smoove] 2024/07/28 23:07:22 removed 653 singletons and isolated interchromosomals of 841 reads (77.65%) from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-hs37d5-D000Q53-FRENCH
WGGAZEL.disc.bam in 0 seconds
[smoove] 2024/07/28 23:07:22 188 reads (10.06%) of the original 1869 remain from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-hs37d5-D000Q53-FRENCHWGGAZEL.disc.bam
[smoove] 2024/07/28 23:07:24 removed 810 alignments out of 1349 (60.04%) with low mapq, depth > 1000, or from excluded chroms from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-
hs37d5-D000Q53-FRENCHWGGAZEL.split.bam in 2 seconds
[smoove] 2024/07/28 23:07:24 removed 320 alignments out of 1349 (23.72%) that were bad interchromosomals or flanked-splitters from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-
hs37d5-D000Q53-FRENCHWGGAZEL.split.bam
[smoove] 2024/07/28 23:07:24 kept 2 putative orphans
[smoove] 2024/07/28 23:07:24 removed 0 split orphans in 0 seconds
[smoove] 2024/07/28 23:07:24 removed 197 singletons of 219 reads (89.95%) from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-hs37d5-D000Q53-FRENCHWGGAZEL.split.bam in 0 seconds
[smoove] 2024/07/28 23:07:24 22 reads (1.63%) of the original 1349 remain from 20231124-SCN5A-THORAX-u1087-chr3_38000000_39500000-hs37d5-D000Q53-FRENCHWGGAZEL.split.bam
[smoove] 2024/07/28 23:07:24 starting lumpy
[smoove] 2024/07/28 23:07:24 wrote lumpy command to results-smoove//D000Q53-lumpy-cmd.sh
[smoove] 2024/07/28 23:07:24 writing sorted, indexed file to results-smoove/D000Q53-smoove.genotyped.vcf.gz
[smoove] 2024/07/28 23:07:24 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2024/07/28 23:07:24 > gsort version 0.1.4
[smoove] 2024/07/28 23:07:24 chr3       1000000
chr3    2000000
chr3    4000000
chr3    8000000
chr3    16000000
chr3    32000000
chr3    64000000
[smoove] 2024/07/28 23:07:24 Calculating library metrics from /projects/0/brugada/NantesBrS/SCN5AregionNantesCRAMs/20231124.SCN5A.THORAX.u1087.chr3_38000000_39500000.hs37d5/20231124.
SCN5A.THORAX.u1087.chr3_38000000_39500000.hs37d5.D000Q53.FRENCHWGGAZEL.cram...
[smoove] 2024/07/28 23:07:27  done
[smoove] 2024/07/28 23:07:27 Writing library metrics to /scratch-local/lipova.7212697/tempclean-557976186/835475816svtype-lib...
[smoove] 2024/07/28 23:07:27  done
[smoove] 2024/07/28 23:07:27 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation
[smoove] 2024/07/28 23:07:27  code=0x1 addr=0x8 pc=0x546d43]

goroutine
[smoove] 2024/07/28 23:07:27 1 [running
[smoove] 2024/07/28 23:07:27 ]:
[smoove] 2024/07/28 23:07:27 bufio.NewReaderSize(...)
        /home/brentp/go/src/bufio/bufio.go:49
bufio.NewReader(...)
        /home/brentp/go/src/bufio/bufio.go:62
[smoove] 2024/07/28 23:07:27 github.com/brentp/gsort.Sort(0x7ad380, 0x0,
[smoove] 2024/07/28 23:07:27 0x7ad3a0, 0xc0000af900
[smoove] 2024/07/28 23:07:27 , 0xc0000af8c0, 0xaf0
[smoove] 2024/07/28 23:07:27 , 0x0, 0x0
[smoove] 2024/07/28 23:07:27 , 0x0)
[smoove] 2024/07/28 23:07:27    /home/brentp/go/go/src/github.com/brentp/gsort/gsort.go:116
[smoove] 2024/07/28 23:07:27  +0x63
[smoove] 2024/07/28 23:07:27 main.main
[smoove] 2024/07/28 23:07:27 ()

[smoove] 2024/07/28 23:07:27 /home/brentp/go/go/src/github.com/brentp/gsort/cmd/gsort/gsort.go:373 +
[smoove] 2024/07/28 23:07:27 0x513
[smoove] 2024/07/28 23:07:27 Failed to read from standard input: unknown file type
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
        /home/brentp/src/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xc14cc0, 0xc0041ce0e0, 0x7ffe858c18b6, 0x4e, 0xc0001d25e0, 0x1, 0x1, 0x7ffe858c188f, 0xf, 0x7ffe858c18a6, ...)
        /home/brentp/src/smoove/svtyper/svtyper.go:226 +0x190a
github.com/brentp/smoove/lumpy.Main()
        /home/brentp/src/smoove/lumpy/lumpy.go:363 +0x4ab
main.main()
        /home/brentp/src/smoove/cmd/smoove/smoove.go:121 +0x1c4"
```

**Comment by Neo-xbx-00** [comment]
I have the same question with you...

**Comment by Alexei-Lipov** [comment]
I found that when I cut the BAMs to a 1.5 Mb region, I lost the mates of certain reads. When I used --fetch-pairs during the BAM cutting process, a particular SV caller I was using (MELT) started to work (I didn't re-try Smoove)

**Comment by brentp** [comment]
hi,as you found, smoove won't work very well on such a small region. It is intended for WGS.
