### ISSUE TITLE
smoove genotype error, panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kuangzhuoran** [brentp/smoove#250]
[smoove] 2024/10/09 09:14:26 starting with version 0.2.8
[smoove] 2024/10/09 09:14:26 writing sorted, indexed file to smoove.genotyped/CE2.joint-smoove.genotyped.vcf.gz
[smoove] 2024/10/09 09:14:26 > gsort version 0.1.4
[smoove] 2024/10/09 09:21:21 [smoove] 2024/10/09 09:21:21 starting with version 0.2.8
[smoove] 2024/10/09 09:21:21 [smoove] 2024/10/09 09:21:21 running duphold on 1 files in 160 processes
[smoove] 2024/10/09 09:21:21 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=
[smoove] 2024/10/09 09:21:21 0x1 addr=0x0 pc=0x4de7fb]

goroutine 37 [running]:
[smoove] 2024/10/09 09:21:21 os.(*Process).signal(0x0, 0xc196f8, 0xef2300, 0x0, 0x0)
	/home/brentp/go/go/src/os/exec_unix.go:63 +0x3b
[smoove] 2024/10/09 09:21:21 os.(*Process).Signal(...)
	/home/brentp/go/go/src/os/exec.go:
[smoove] 2024/10/09 09:21:21 135
os.(*Process).kill(...)
	/home/brentp/go/go/src/os/exec_posix.go:66
os.(*Process).Kill(...)
	/home/brentp/go/go/src/os/exec.go:120
github.com/brentp/smoove/duphold.Main.func2(0xc0003d0000, 0xc00032e7f8, 0xc0003177b0, 0xc000310120, 0xc0003481f8, 0xc00032e810, 0xc000319fb0)
	/home/brentp/src/smoove/duphold/duphold.go:96 +0x595
created by github.com/brentp/smoove/duphold.Main
	/home/brentp/src/smoove/duphold/duphold.go:79 +0x4d2
2024/10/09 09:21:21 exit status 2

**Comment by brentp** [comment]
is this on a cluster? is it possible you are running out of memory?
