### ISSUE TITLE
invalid coodinates star: start > stop

### ISSUE THREAD

**Issue by sbamin** [brentp/smoove#29]
Hi @brentp,

While running `smoove call` using two samples (tumor-normal), I get exit 0 for most but a few samples having following error:

```
[smoove] 2018/10/16 09:22:28 AAEX03026072.1	1000000
[smoove] 2018/10/16 15:16:38 Traceback (most recent call last):
  File "/projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/bin/svtyper", line 11, in <module>
[smoove] 2018/10/16 15:16:38     load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
  File "/projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/lib/python2.7/site-packages/svtyper/classic.py", line 575, in cli
    sys.exit(main())
  File "/projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/lib/python2.7/site-packages/svtyper/classic.py", line 568, in main
    args.max_ci_dist)
  File "/projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/lib/python2.7/site-packages/svtyper/classic.py", line 281, in sv_genotype
    read_batch, many = gather_all_reads(sample, chromA, posA, ciA, chromB, posB, ciB, z, max_reads)
  File "/projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/lib/python2.7/site-packages/svtyper/classic.py", line 61, in gather_all_reads
    read_batch, many = gather_reads(sample, chromB, posB, ciB, z, read_batch, max_reads)
  File "/projects/verhaak-lab/verhaak_env/anaconda/v4.2.0/lib/python2.7/site-packages/svtyper/classic.py", line 81, in gather_reads
    min(pos + ci[1] + fetch_flank, chrom_length))):
  File "pysam/libcalignmentfile.pyx", line 1074, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 690, in pysam.libchtslib.HTSFile.parse_region
[smoove] 2018/10/16 15:16:38 ValueError: invalid coordinates: start (8766133) > stop (16727)
panic: exit status 1

goroutine 11201382 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper.func2(0xc3dfae4a80, 0xc00000af60, 0x2, 0x2, 0x7ffdf7eb2835, 0x32, 0xc00017a0b0, 0xc0001801b8, 0xc000180230, 0xc0000c8040, ...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:175 +0x5ed
created by github.com/brentp/smoove/svtyper.Svtyper
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:166 +0xb70
LOGGER	16Oct18_151639EDT	smoove_paired_runner	END	S01-FCD0-A2_paired	/gpfs/ctgs0/fastscratch/amins/svcalls/smoove/paired_runner/S01-FCD0-A2_paired	2
END at Tue Oct 16 15:16:39 EDT 2018
```

Command I'd executed:

```sh
smoove call \
--removepr \
--support 3 \
--processes 3 \
--genotype \
--name S01-FCD0-A2_paired \
--outdir /fastscratch/amins/svcalls/smoove/paired_genotyped_calls \
--exclude gaps_ucsc_table_canfam3.1.sorted.bed \
--excludechroms '~^AA,~^JH' \
--fasta /projects/verhaak-lab/DogWGSReference/CanFam3_1.fa \
/projects/verhaak-lab/L1SEQ/cgp_level1_bams/CGP-S01-FCD0-05212240-T6-A2-J01.aln.dup.realn.recal.rp.bam /projects/verhaak-lab/L1SEQ/cgp_level1_bams/CGP-S01-FCD0-B797658F-T1-A2-J01.aln.dup.realn.recal.rp.bam
```

I checked resulting vcf.gz from two cases with error and case with exit 0. For a case without any error, looks like `--excludechroms '~^AA,~^JH'` did not work for me as I see a few (1-5) SV calls from non-canonical chromosomes/scaffolds. For two cases with above error,  I see sv calls for all of canonical chromosomes for one case while no SV calls at all for an another case.

Since I am only interested in canonical chromosomes, I think I can safely ignore this error for cases where I have SV calls from canonical chromosomes while rerun samples where smoove ouptut zero calls. I don't see smoove running more steps after emitting calls to vcf but just want to make sure that error was emitted **after** (~ 6 hr runtime) traversing all of canonical chromosomes, and so I have error-free smoove run from canonical chromosomes.

```
[smoove] 2018/10/16 09:22:28 AAEX03026072.1	1000000
[smoove] 2018/10/16 15:16:38 Traceback (most recent call last):
```

Thanks,
Samir

[detailed log](https://gist.github.com/sbamin/7af42588b6eba3243d6b2135d1eb2a3f)

**Comment by sbamin** [comment]
To follow up, I reran same command again, and this time it was able to write final vcf (with entries until the errored chromosome scaffold). It returned exit 0 but with following segmentation fault.

```
[smoove] 2018/10/17 07:57:19 AAEX03021043.1	1000000
[smoove] 2018/10/17 07:57:27 bash: line 1: 14936 Segmentation fault      (core dumped) lumpy -msw 3 -mw 3 -t $(mktemp) -tt 0 -P -pe id:CGP-S01-FCD0-05212240-T6-A2-J01,bam_file:/fastscratch/amins/svcalls/smoove/paired_genotyped_calls/CGP-S01-FCD0-05212240-T6-A2-J01.disc.bam,histo_file:/fastscratch/amins/svcalls/smoove/paired_genotyped_calls/CGP-S01-FCD0-05212240-T6-A2-J01.histo,mean:156.36,stdev:76.14,read_length:150,min_non_overlap:150,discordant_z:4,back_distance:30,weight:1,min_mapping_threshold:20 -sr id:CGP-S01-FCD0-05212240-T6-A2-J01,bam_file:/fastscratch/amins/svcalls/smoove/paired_genotyped_calls/CGP-S01-FCD0-05212240-T6-A2-J01.split.bam,back_distance:10,weight:1,min_mapping_threshold:20 -pe id:CGP-S01-FCD0-B797658F-T1-A2-J01,bam_file:/fastscratch/amins/svcalls/smoove/paired_genotyped_calls/CGP-S01-FCD0-B797658F-T1-A2-J01.disc.bam,histo_file:/fastscratch/amins/svcalls/smoove/paired_genotyped_calls/CGP-S01-FCD0-B797658F-T1-A2-J01.histo,mean:156.35,stdev:75.66,read_length:150,min_non_overlap:150,discordant_z:4,back_distance:30,weight:1,min_mapping_threshold:20 -sr id:CGP-S01-FCD0-B797658F-T1-A2-J01,bam_file:/fastscratch/amins/svcalls/smoove/paired_genotyped_calls/CGP-S01-FCD0-B797658F-T1-A2-J01.split.bam,back_distance:10,weight:1,min_mapping_threshold:20
[smoove] 2018/10/17 07:59:44 wrote sorted, indexed file to /fastscratch/amins/svcalls/smoove/paired_genotyped_calls/S01-FCD0-A2_paired-smoove.genotyped.vcf.gz
LOGGER	17Oct18_075944EDT	smoove_paired_runner	END	S01-FCD0-A2_paired	/gpfs/ctgs0/fastscratch/amins/svcalls/smoove/paired_runner/S01-FCD0-A2_paired	0
END at Wed Oct 17 07:59:44 EDT 2018
exit status was 0
```

**Comment by brentp** [comment]
can you share a cram so I can debug?

**Comment by sbamin** [comment]
I do have bam output for split and discordant reads, and just sent globus download link to your gmail.

**Comment by brentp** [comment]
I believe this has been resolved. Please reopen if that is not the case.
