### ISSUE TITLE
Suggestion: Fail more gracefully if folder not given

### ISSUE THREAD

**Issue by davemcg** [brentp/smoove#33]
Definitely in the "minor" category, but makes for a jarring experience. 
```
[mcgaugheyd@cn3211 2018-09-24]$ smoove call --name 1238 --fasta /fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta --excludechroms hs37d5 -p 2 --outdir TEST_1238 --genotype --duphold sample_cram/1238.cram
[smoove] 2018/11/14 01:30:15 starting with version 0.1.11
[smoove] 2018/11/14 01:30:15 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2018/11/14 01:30:16 [E::hts_open_format] fail to open file 'TEST_1238/1238.disc.bam.tmp.bam'
[smoove]:([E]lumpy-filter) 2018/11/14 01:30:16 [E::hts_open_format] fail to open file 'TEST_1238/1238.split.bam.tmp.bam'
[smoove]:([E]lumpy-filter) 2018/11/14 01:30:16 /bin/bash: line 1: 33749 Segmentation fault      lumpy_filter -f /fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta sample_cram/1238.cram TEST_1238/1238.split.bam.tmp.bam TEST_1238/1238.disc.bam.tmp.bam 2
[smoove]:2018/11/14 01:30:16 finished process: lumpy-filter (lumpy_filter -f /fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta sample_cram/1238.cram TE) in user-time:11.854ms system-time:99.86ms
[smoove]:2018/11/14 01:30:16 error running command: lumpy_filter -f /fdb/GATK_resource_bundle/b37-2.8/human_g1k_v37_decoy.fasta sample_cram/1238.cram TEST_1238/1238.split.bam.tmp.bam TEST_1238/1238.disc.bam.tmp.bam 2 && mv TEST_1238/1238.split.bam.tmp.bam TEST_1238/1238.split.bam && mv TEST_1238/1238.disc.bam.tmp.bam TEST_1238/1238.disc.bam -> exit status 139

panic: open TEST_1238/1238.histo: no such file or directory

goroutine 27 [running]:
github.com/brentp/smoove/lumpy.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:53
github.com/brentp/smoove/lumpy.filter.write_hist(0x7fffffffc79e, 0x15, 0xc0001743a0, 0x18, 0xc0001743c0, 0x17, 0xc0001ae000, 0x122, 0x7fffffffc7aa, 0x4, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:72 +0x219
github.com/brentp/smoove/lumpy.bam_stats.func1(0x1)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:192 +0x25a
created by github.com/brentp/smoove/lumpy.bam_stats
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:198 +0x1a2
```

After doing `mkdir TEST_1238` it is running fine. 

Perhaps create the folder or check if folder exists?

**Comment by brentp** [comment]
you have a pretty old version of smoove. recent releases have fixed this so that it does make the outdir if it does not exist.

**Comment by davemcg** [comment]
Yeah....HPC people installed 0.1.11 but labelled it as 0.2.1
