### ISSUE TITLE
index: unrecognized option '--threads'

### ISSUE THREAD

**Issue by dfermin** [brentp/smoove#44]
Hello.
I just got smoove installed on our system but I'm unable to get through a test case.
I'm running the whole pipeline on just chromosome 22 for testing purposes.

Here is the output of the smoove command:
<pre>

smoove version: 0.2.2

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools
 *[Y] svtyper
 *[Y] mosdepth [extra filtering of split and discordant files for better scaling]

  [Y] duphold [(optional) annotate calls with depth changes]
  [Y] svtools [only needed for large cohorts].
</pre>

Then execute these commands:
<pre>
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/smoove/bin ## for libhts.so
smoove call --outdir results-smoove/ --name samp_001.chr22 --fasta /nfs/conf/hs37d5.fa --genotype bam.files/samp_001.chr22.bam
</pre>

This is the output I get:
<pre>
[smoove] 2018/12/11 10:26:38 starting with version 0.2.2
[smoove] 2018/12/11 10:26:38 calculating bam stats for 1 bams
[smoove] 2018/12/11 10:26:49 done calculating bam stats
[smoove] 2018/12/11 10:26:50 removed 0 alignments out of 7639 (0.00%) with low mapq, depth > 1000, or from excluded chroms from samp_001.split.bam in 1 seconds
[smoove] 2018/12/11 10:26:50 removed 0 alignments out of 7639 (0.00%) that were bad interchromosomals or flanked-splitters from samp_001.split.bam
[smoove] 2018/12/11 10:26:50 removed 0 singletons of 7639 reads (0.00%) from samp_001.split.bam in 0 seconds
[smoove] 2018/12/11 10:26:50 7639 reads (100.00%) of the original 7639 remain from samp_001.split.bam
[smoove] 2018/12/11 10:26:50 removed 0 alignments out of 5893 (0.00%) with low mapq, depth > 1000, or from excluded chroms from samp_001.disc.bam in 1 seconds
[smoove] 2018/12/11 10:26:50 removed 0 alignments out of 5893 (0.00%) that were bad interchromosomals or flanked-splitters from samp_001.disc.bam
[smoove] 2018/12/11 10:26:50 removed 0 singletons and isolated interchromosomals of 5893 reads (0.00%) from samp_001.disc.bam in 0 seconds
[smoove] 2018/12/11 10:26:50 5893 reads (100.00%) of the original 5893 remain from samp_001.disc.bam
[smoove] 2018/12/11 10:26:50 starting lumpy
[smoove] 2018/12/11 10:26:50 wrote lumpy command to results-smoove//samp_001_chr22-lumpy-cmd.sh
[smoove] 2018/12/11 10:26:50 writing sorted, indexed file to results-smoove/samp_001_chr22-smoove.genotyped.vcf.gz
[smoove] 2018/12/11 10:26:50 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2018/12/11 10:26:51 > gsort version 0.0.6
[smoove] 2018/12/11 10:26:51 22	1000000
[smoove] 2018/12/11 10:26:51 22	2000000
22	4000000
22	8000000
22	16000000
22	32000000
[smoove] 2018/12/11 10:27:10 index: unrecognized option '--threads'

About:   Index bgzip compressed VCF/BCF files for random access.
Usage:   bcftools index [options] <in.bcf>|<in.vcf.gz>

Indexing options:
    -c, --csi            generate CSI-format index for VCF/BCF files [default]
    -f, --force          overwrite index if it already exists
    -m, --min-shift INT  set minimal interval size for CSI indices to 2^INT [14]
    -t, --tbi            generate TBI-format index for VCF files

Stats options:
    -n, --nrecords       print number of records based on existing index file
    -s, --stats   print per contig stats based on existing index file

panic: exit status 1

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xa840c0, 0xc00000c110, 0x7ffe50e533b6, 0x23, 0xc00016e640, 0x1, 0x1, 0x7ffe50e53387, 0xf, 0x7ffe50e5339e, ...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:224 +0x18c6
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:332 +0x433
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:123 +0x1d7
</pre>

I'm not sure what is wrong. Obviously it's choking at a bcftools command and elsewhere but I can't find the source.

The bam file I'm giving it looks fine. It runs to completion through lumpy with no issues.

Any suggests would be welcome.
Thanks!

**Comment by brentp** [comment]
hi, you'll have to update your version of bcftools. The --threads option is in recent versions. I'd be glad to accept a PR that checks for the required bcftools version.
