### ISSUE TITLE
Error in lumpy_filter step

### ISSUE THREAD

**Issue by kpjonsson** [brentp/smoove#59]
I'm trying to run smoove on a set of tumor-normal pairs as outlined here: https://github.com/brentp/smoove/issues/26

My call is:
```shell
smoove call \
        -x \
        --name sample_name \
        --outdir structural_variants/smoove \
        --exclude ceph18.b37.lumpy.exclude.2014-01-15.bed \
        --fasta ref.fa \
        --processes 6 \
        --support 3 \
        --duphold \
        --genotype normal.bam tumor.bam"
```

After the bam stats step, smoove exits with this error message:
```
smoove]:2019/02/19 10:39:50 error running command: set -eu; lumpy_filter -f ref.fa normal.bam structural_variants/smoove/normal.split.bam.tmp.bam structural_variants/smoove/normal.disc.bam.tmp.bam 2 && mv structural_variants/smoove/normal.split.bam.tmp.bam structural_variants/smoove/normal.split.bam && mv structural_variants/smoove/normal.disc.bam.tmp.bam structural_variants/smoove/normal.disc.bam && cp structural_variants/smoove/normal.split.bam structural_variants/smoove/normal.split.bam.orig.bam && cp structural_variants/smoove/normal.disc.bam structural_variants/smoove/normal.disc.bam.orig.bam -> exit status 83
[smoove]:([E]lumpy-filter) 2019/02/19 11:04:23 [lumpy_filter] extracted splits and discordants from 1978285232 total aligned reads
[smoove]:2019/02/19 11:04:23 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/jonssonp/work/ref/b37/b37.fasta bam/tumor.bam structu) in user-time:1h28m10.742684s system-time:5m39.635367s
[smoove]:2019/02/19 11:04:23 error running command: set -eu; lumpy_filter -f ref.fa tumor.bam structural_variants/smoove/tumor.split.bam.tmp.bam structural_variants/smoove/tumor.disc.bam.tmp.bam 2 && mv structural_variants/smoove/tumor.split.bam.tmp.bam structural_variants/smoove/tumor.split.bam && mv structural_variants/smoove/tumor.disc.bam.tmp.bam structural_variants/smoove/tumor.disc.bam && cp structural_variants/smoove/tumor.split.bam structural_variants/smoove/tumor.split.bam.orig.bam && cp structural_variants/smoove/tumor.disc.bam structural_variants/smoove/tumor.disc.bam.orig.bam -> exit status 84
panic: exit status 84

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffe2b6579f2, 0x1b, 0x7ffe2b657a72, 0x25, 0x7ffe2b657a17, 0x1a, 0xc00016a940, 0x2, 0x2, 0xc000170f00, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x5c9
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:334 +0x277
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7
```

The `lumpy_filter` call finishes and produces the `*tmp.bam` files. The individual `mv` and `cp` calls work when I run them after the process exits. Any clue what could be the issue?

**Comment by brentp** [comment]
exit status 84 is a disk write error or something. Your TMPDIR or your output dir is probably filling up. Make sure to set tmpdir (export TMPDIR=/xxx) and your output directory to somewhere with sufficient space.

**Comment by kpjonsson** [comment]
I am explicitly setting my `TMPDIR` variable to a disk with plenty of space. And if I submit it to our compute cluster it is set to scratch directories on the compute nodes that also have plenty of space.
