### ISSUE TITLE
Merge issue

### ISSUE THREAD

**Issue by Thatguy027** [brentp/smoove#62]
Hi there,

I'm in the process of re-running our SV calling pipeline with the latest version of a few callers... smoove got updated to 0.2.3. I'm getting this error when attempting to merge individual VCFs from the first call step:

Command run:
```
smoove merge --fasta /projects/b1059/data/genomes/c_elegans/WS245/WS245.fa --name merged_smoove --outdir . vcf1 vcf2....vcf330
```

Command error:
```
[smoove] 2019/03/17 23:35:30 starting with version 0.2.3
[smoove] 2019/03/17 23:35:30 merging 330 files
[smoove] 2019/03/17 23:35:30 finished sorting 330 files; merge starting.
[smoove] 2019/03/17 23:48:17 Traceback (most recent call last):
  File "/home/szs315/.pyenv/versions/py2-2018-03-09/bin/svtools", line 11, in <module>
[smoove] 2019/03/17 23:48:17     sys.exit(main())
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/cli.py", line 79, in main
[smoove] 2019/03/17 23:48:17     sys.exit(args.entry_point(args))
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/lmerge.py", line 622, in run_from_args
[smoove] 2019/03/17 23:48:17     weighting_scheme=args.weighting_scheme)
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/lmerge.py", line 587, in l_cluster_by_line
[smoove] 2019/03/17 23:48:17     v_id = r_cluster(BP_l, sample_order, v_id, use_product, vcf, vcf_out, include_genotypes, weighting_scheme)
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/lmerge.py", line 518, in r_cluster
[smoove] 2019/03/17 23:48:17     v_id = merge(BP_r, sample_order, v_id, use_product, vcf, vcf_out, include_genotypes, weighting_scheme)
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/lmerge.py", line 493, in merge
[smoove] 2019/03/17 23:48:17     var=create_merged_variant(BP, cliq, v_id, vcf, use_product, weighting_scheme)
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/lmerge.py", line 236, in create_merged_variant
[smoove] 2019/03/17 23:48:17     new_start_L, new_start_R, p_L , p_R, ALG = combine_pdfs(BP, c, use_product, weighting_scheme)
[smoove] 2019/03/17 23:48:17   File "/home/szs315/.pyenv/versions/miniconda3-4.3.27/envs/py2-2018-03-09/lib/python2.7/site-packages/svtools/lmerge.py", line 171, in combine_pdfs
[smoove] 2019/03/17 23:48:17     p_R[i] += a_R[c_i][i]
[smoove] 2019/03/17 23:48:17 IndexError: 
[smoove] 2019/03/17 23:48:17 list index out of range
```

Any thoughts as to what the issue might be? I ran into a conda/pyenv issue at the call step that I had to sort out, I am wondering if this might be a similar situation.

smoove can find all dependencies:

```
smoove version: 0.2.3

smoove calls several programs. Those with 'Y' are found on your $PATH. Only those with '*' are required.

 *[Y] bgzip [ sort   -> (compress) ->   index ]
 *[Y] gsort [(sort)  ->  compress   ->  index ]
 *[Y] tabix [ sort   ->  compress   -> (index)]
 *[Y] lumpy
 *[Y] lumpy_filter
 *[Y] samtools
 *[Y] svtyper
 *[Y] mosdepth [extra filtering of split and discordant files for better scaling]

  [Y] duphold [(optional) annotate calls with depth changes]
  [Y] svtools [only needed for large cohorts].
```

Thanks for your feedback!

**Comment by brentp** [comment]
hmm. nothing obvious jumps out. can you bisect the files and see if there's a single one that is responsible? or maybe you can run e.g. `bcftools view` on each and see if it detects any broken/truncated files?

**Comment by Thatguy027** [comment]
Just looped through all the VCFs with no issue:

```
for vcf in *.vcf.gz
do
	echo $vcf
	bcftools view $vcf -Oz -o temp.vcf.gz
	rm temp.vcf.gz
	echo done $vcf
done
```

Is this what you had in mind?

Just took a look at the README, and it mentions `smoove call` only works with `-p` set to 2-3. I have mine set at 6, do you think this might be the source of the issue? Figured I'd ask before re-running with `-p 1` because there was no issue reading the VCFs with `bcftools`.

**Comment by brentp** [comment]
that seems fine, as long as you used `set -e` so you'd see an error.

The only other quick check I can think of is to see if all the files have a .csi ? hopefully one of them is missing it.

I guess I would try a bisect approach to find if a single file is responsible. Looks like it errors after <13 minutes with the full set so it won't be fun, but should be possible to find the problematic file.

**Comment by Thatguy027** [comment]
A .csi file you say?! Nope, none of the files have an index! 

The pipeline didn't require it before from what I can tell (I didn't include index files in the output from the call step previously), but I guess it does now. I notice that `smoove call` generated the index files, so I will just transfer them to the `merge` step... then try the bisect approach if the issue persists. I'm hoping it doesn't!

Does `smoove merge` generate an index too? I'll probably have to include that into the `genotype` step as well.

**Comment by brentp** [comment]
the CSI's should be required, but it does generate them. The absence of one would be an indicator that file was bad.

**Comment by brentp** [comment]
I mean the CSI' should **NOT** be required.

**Comment by Thatguy027** [comment]
Oh ok, I transferred the csi files anyway and there is a corresponding index for ever sample VCF, which I take to mean that the files are good from your previous reply... got the same error, which makes sense because you said the index files should **NOT** be necessary.

Now, I am wondering if it is a chromosome name issue - the chromosome names I am working with are: I, II, III, IV, V, X, MtDNA, which I think is different than human annotations. Usually, the mitochondrial genome is at the end of the VCF file, which is the case for individual sample VCFs generated by `smoove call`:

```
bcftools view N2-smoove.genotyped.vcf.gz | tail -1
MtDNA	10	439	N	<DUP>	6259.03	.	SVTYPE=DUP;SVLEN=13784;END=13794;STRANDS=-+:339;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=339;PE=111;SR=228;PRPOS=1;PREND=1;AC=2;AN=2	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	1/1:200:6259.03:-822,-287,-196:412:0:412:0:411:0:115:48:0:247:1
```

But not the case for the intermediate merged and sorted VCF generated by `smoove merge`:

```
tail -1 merged_smoove.lsort.vcf 
X	17717958	1679_1	N	<INV>	731.54	.	SVTYPE=INV;STRANDS=++:27,--:0;CIPOS=-10,9;CIEND=-2,0;CIPOS95=0,0;CIEND95=0,0;MATEID=1679_2;EVENT=1679;SU=27;PE=9;SR=18;PRPOS=2.60325e-82,4.79526e-74,8.83265e-66,1.62662e-57,2.99572e-49,5.51611e-41,1.01561e-32,1.86973e-24,3.4421e-16,6.33653e-08,1,6.17312e-08,3.80885e-15,2.34898e-22,1.44699e-29,8.91143e-37,5.48852e-44,3.37977e-51,2.08174e-58,1.28028e-65;PREND=2.35999e-15,6.60642e-08,1;AC=1;AN=2;SNAME=XZ1735;END=17718763	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:105:731.54:-74,-1,-12:59:27:31:26:30:17:19:0:9:11:0.54
```

Mitochondrial sites are in the merged and sorted VCF, but they don't appear to be sorted by position (and they are not at the end)...

```
grep MtDNA merged_smoove.lsort.vcf | head -10
##contig=<ID=MtDNA,length=13794>
MtDNA	449	3145	N	<DEL>	14582.1	.	SVTYPE=DEL;SVLEN=-11566;END=12015;STRANDS=+-:491;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=491;PE=263;SR=228;PRPOS=1;PREND=1;AC=1;AN=2;SNAME=PS2025	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:200:14582.1:-1625,-167,-1568:3095:2297:797:2296:796:1240:227:139:1056:429:0.26
MtDNA	1786	1214	N	<DEL>	38569.4	.	SVTYPE=DEL;SVLEN=-541;END=2327;STRANDS=+-:152;IMPRECISE;CIPOS=-13,20;CIEND=-150,29;CIPOS95=-3,3;CIEND95=-8,2;SU=152;PE=152;SR=0;PRPOS=2.65547e-15,2.83099e-13,1.14991e-11,4.49909e-10,1.2623e-08,2.5337e-07,3.63044e-06,5.09511e-05,0.000512055,0.00499783,0.035062,0.0947521,0.248937,0.252667,0.184143,0.129875,0.0360502,0.00957263,0.00251121,0.00064711,0.000164229,4.08246e-05,1.00012e-05,2.39995e-06,5.64382e-07,1.31432e-07,3.06818e-08,7.05321e-09,1.61469e-09,3.7245e-10,8.51906e-11,1.94017e-11,4.49738e-12,1.02487e-12;PREND=3.76232e-118,3.14359e-116,2.19216e-114,1.8937e-112,1.77624e-110,1.90164e-108,2.42539e-106,3.70604e-104,5.99887e-102,1.13661e-99,2.40641e-97,5.10577e-95,1.07913e-92,2.39637e-90,5.39866e-88,1.26146e-85,2.89222e-83,6.89956e-81,1.36995e-78,2.81931e-76,5.13094e-74,8.98037e-72,1.41096e-69,2.05994e-67,2.55013e-65,2.95161e-63,3.00344e-61,2.66464e-59,2.24655e-57,1.63256e-55,1.04323e-53,5.85449e-52,2.81851e-50,1.11415e-48,3.85856e-47,1.14943e-45,2.8883e-44,6.37947e-43,1.16189e-41,1.91954e-40,2.75864e-39,3.33888e-38,3.52315e-37,3.27918e-36,2.69951e-35,1.99544e-34,1.34086e-33,8.21839e-33,4.61635e-32,2.36368e-31,1.17326e-30,5.34669e-30,2.3311e-29,9.68339e-29,3.8544e-28,1.48712e-27,5.47076e-27,1.97444e-26,7.01739e-26,2.41724e-25,8.22368e-25,2.74381e-24,9.15301e-24,2.93641e-23,9.42149e-23,2.99071e-22,9.23475e-22,2.85679e-21,8.74232e-21,2.62166e-20,7.73212e-20,2.27745e-19,6.5369e-19,1.86608e-18,5.20642e-18,1.44643e-17,3.97192e-17,1.06699e-16,2.83044e-16,7.369e-16,1.88715e-15,4.72022e-15,1.15479e-14,2.79452e-14,6.64968e-14,1.54713e-13,3.50057e-13,7.80269e-13,1.73303e-12,3.76689e-12,7.99346e-12,1.67244e-11,3.38804e-11,6.77752e-11,1.31589e-10,2.51232e-10,4.64694e-10,8.60552e-10,1.54555e-09,2.71328e-09,4.70618e-09,7.97597e-09,1.3295e-08,2.18855e-08,3.53014e-08,5.65707e-08,8.91746e-08,1.37687e-07,2.09737e-07,3.15924e-07,4.7121e-07,7.01366e-07,1.02802e-06,1.49756e-06,2.14612e-06,3.06099e-06,4.31404e-06,6.05444e-06,8.48372e-06,1.19362e-05,1.66824e-05,2.3029e-05,3.20001e-05,4.42145e-05,6.07498e-05,8.39121e-05,0.000115086,0.000157103,0.000217206,0.000296115,0.00040354,0.000550532,0.000754444,0.0010369,0.00142335,0.00193377,0.00261855,0.00354694,0.00483057,0.00651495,0.00880649,0.01192,0.0161379,0.021891,0.02939,0.0395717,0.0532456,0.0721974,0.0967952,0.131356,0.176416,0.173727,0.143845,4.05187e-17,1.14318e-32,3.22631e-48,9.08314e-64,1.87763e-79,2.85786e-95,4.34516e-111,6.60586e-127,1.00465e-142,1.52799e-158,2.32191e-174,3.52586e-190,5.33396e-206,4.35343e-222,2.61043e-238,1.56342e-254,9.35398e-271,5.59001e-287,3.3371e-303,1.9899e-319,0,0,0,0,0,0,0;AC=1;AN=2;SNAME=JU1249	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:200:38569.4:-4037,-180,-2543:5952:4068:1883:4067:1882:3051:648:307:1016:927:0.32
MtDNA	3348	2309	N	<DEL>	37688.8	.	SVTYPE=DEL;SVLEN=-1059;END=4407;STRANDS=+-:782;IMPRECISE;CIPOS=-2,7;CIEND=-9,11;CIPOS95=0,1;CIEND95=-1,3;SU=782;PE=782;SR=0;PRPOS=5.04825e-19,1.06347e-09,0.864573,0.129266,0.00595795,0.000196444,6.33162e-06,2.0166e-07,6.24951e-09,1.93734e-10;PREND=9.48808e-13,2.4822e-11,6.42117e-10,1.60956e-08,4.01445e-07,9.64992e-06,0.000229177,0.00531281,0.120647,0.425724,0.235622,0.128538,0.0514799,0.0201708,0.00778081,0.00287239,0.00105093,0.000372569,0.00013166,4.65254e-05,1.13339e-05;AC=1;AN=2;SNAME=NIC258	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:200:37688.8:-3852,-84,-1790:4818:3077:1740:3076:1739:1802:464:200:1274:1074:0.36
MtDNA	4418	3655	N	<DEL>	40347.9	.	SVTYPE=DEL;SVLEN=-1600;END=6018;STRANDS=+-:1262;CIPOS=0,0;CIEND=0,0;CIPOS95=0,0;CIEND95=0,0;SU=1262;PE=701;SR=561;PRPOS=1;PREND=1;AC=1;AN=2;SNAME=JU2001	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:200:40347.9:-4155,-120,-2166:5519:3620:1899:3619:1898:1919:575:363:1700:959:0.34
MtDNA	29	3250	N	<DUP>	13237.6	.	SVTYPE=DUP;SVLEN=13764;END=13793;STRANDS=-+:181;IMPRECISE;CIPOS=-29,0;CIEND=-2,25;CIPOS95=-29,0;CIEND95=0,3;SU=181;PE=181;SR=0;PRPOS=1.19629e-55,1.38006e-53,3.06336e-51,9.21889e-49,1.22553e-46,2.7468e-44,3.88485e-42,2.30734e-40,2.69912e-38,2.07403e-36,3.31241e-34,3.08354e-32,2.33884e-30,3.54939e-28,1.76095e-26,1.48726e-24,1.09846e-22,7.04253e-21,2.95571e-19,8.37964e-18,3.22159e-16,9.76755e-15,5.88646e-13,2.89953e-11,9.45001e-10,3.04926e-08,1.01734e-06,3.11717e-05,0.00163554,0.0478827;PREND=1.07803e-23,2.43636e-12,0.543552,0.299212,0.102932,0.0357385,0.0122371,0.00417775,0.00142179,0.000483271,0.000162441,5.4898e-05,1.84929e-05,6.18893e-06,2.06837e-06,6.9222e-07,2.31751e-07,7.75446e-08,2.54167e-08,8.35842e-09,2.7702e-09,9.2315e-10,3.04691e-10,1.00229e-10,3.27815e-11,1.07133e-11,3.50475e-12,1.12623e-12;AC=2;AN=2;SNAME=QG2832	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	1/1:200:13237.6:-1333,-112,-10:2724:1666:1057:1665:1057:1257:506:104:408:446:0.39
MtDNA	29	3750	N	<DUP>	16433.8	.	SVTYPE=DUP;SVLEN=13764;END=13793;STRANDS=-+:233;IMPRECISE;CIPOS=-29,0;CIEND=-1,20;CIPOS95=-29,0;CIEND95=0,2;SU=233;PE=233;SR=0;PRPOS=6.10391e-72,6.68698e-69,3.87263e-66,5.05617e-63,8.421e-60,1.76547e-57,4.63531e-55,1.20931e-52,9.78046e-50,5.59962e-47,2.77201e-44,8.18975e-42,3.20019e-39,6.69929e-37,1.67185e-34,1.79955e-32,5.55881e-30,1.00349e-27,1.84025e-25,2.33611e-23,3.33543e-21,4.5308e-19,8.21216e-17,1.04953e-14,1.35059e-12,1.41244e-10,1.53974e-08,1.8017e-06,0.000160623,0.00979268;PREND=2.5522e-14,0.629009,0.27686,0.0702412,0.0178603,0.00452498,0.00113169,0.000280889,6.94806e-05,1.70336e-05,4.1622e-06,1.02191e-06,2.47078e-07,6.05154e-08,1.46273e-08,3.55437e-09,8.59017e-10,2.06023e-10,5.01039e-11,1.20518e-11,2.8986e-12,6.90016e-13;AC=2;AN=2;SNAME=QG2846	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	1/1:200:16433.8:-1668,-170,-25:3014:1738:1276:1737:1275:1331:579:141:406:554:0.42
MtDNA	29	3290	N	<DUP>	15626.7	.	SVTYPE=DUP;SVLEN=13764;END=13793;STRANDS=-+:204;IMPRECISE;CIPOS=-29,0;CIEND=-1,24;CIPOS95=-29,0;CIEND95=0,2;SU=204;PE=204;SR=0;PRPOS=1.76227e-61,5.30097e-59,1.16522e-56,6.02758e-54,1.05797e-51,1.03004e-48,3.12926e-46,9.07884e-44,1.52842e-41,1.72116e-39,2.26512e-37,5.48096e-35,6.43875e-33,6.45287e-31,7.59711e-29,8.40182e-27,9.82335e-25,4.42856e-23,2.99944e-21,1.97138e-19,2.0171e-17,5.90786e-16,5.4673e-14,5.22109e-12,2.13874e-10,9.03879e-09,3.10168e-07,9.84852e-06,0.00034106,0.0182087;PREND=1.78428e-17,0.523346,0.322791,0.103896,0.034006,0.0108281,0.00347348,0.00113033,0.00035839,0.000115856,3.71757e-05,1.19436e-05,3.71493e-06,1.18693e-06,3.70926e-07,1.17085e-07,3.62701e-08,1.11739e-08,3.41546e-09,1.05229e-09,3.268e-10,9.92424e-11,3.11016e-11,9.48892e-12,2.88881e-12,8.79102e-13;AC=2;AN=2;SNAME=QG2932	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	1/1:200:15626.7:-1577,-141,-14:3109:1871:1238:1870:1237:1418:562:149:452:525:0.4
MtDNA	29	2961	N	<DUP>	22397.4	.	SVTYPE=DUP;SVLEN=13764;END=13793;STRANDS=-+:457;IMPRECISE;CIPOS=-29,0;CIEND=-1,30;CIPOS95=-29,0;CIEND95=-30,1;SU=457;PE=457;SR=0;PRPOS=4.15867e-127,1.06257e-121,3.31541e-117,2.56036e-112,4.73162e-108,1.34253e-103,1.35467e-98,6.43046e-94,5.61787e-90,1.17911e-85,2.21674e-81,3.72764e-77,7.13383e-73,1.14561e-68,3.10269e-64,4.734e-60,2.12177e-55,2.30638e-51,3.51829e-47,4.09093e-43,4.30107e-39,3.49439e-35,3.92592e-31,1.69746e-27,2.47706e-23,1.52537e-19,5.81993e-16,3.93972e-12,3.04837e-08,0.000171944;PREND=1.60928e-26,0.517622,0.273321,0.118853,0.0512875,0.0222495,0.00958748,0.00407559,0.00173934,0.0007356,0.000308386,0.000128668,5.39538e-05,2.24921e-05,9.3554e-06,3.89414e-06,1.57965e-06,6.4488e-07,2.58895e-07,1.04244e-07,4.18105e-08,1.6658e-08,6.53548e-09,2.56996e-09,9.92847e-10,3.83135e-10,1.49313e-10,5.66102e-11,2.13742e-11,8.04497e-12,2.96918e-12,1.10362e-12;AC=2;AN=2;SNAME=WN2050	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	1/1:200:22397.4:-2256,-191,-16:4574:2788:1785:2787:1785:2010:724:186:777:874:0.39
MtDNA	71	2807	N	<DUP>	21556.9	.	SVTYPE=DUP;SVLEN=13651;END=13722;STRANDS=-+:16;IMPRECISE;CIPOS=-71,0;CIEND=-24,185;CIPOS95=-71,0;CIEND95=-5,55;SU=16;PE=16;SR=0;PRPOS=9.30547e-19,1.46592e-18,2.32654e-18,3.68977e-18,5.89653e-18,9.40243e-18,1.51183e-17,2.45265e-17,3.90897e-17,6.30142e-17,1.00211e-16,1.61933e-16,2.60977e-16,4.25273e-16,6.91921e-16,1.12595e-15,1.82524e-15,3.0142e-15,5.01815e-15,8.26965e-15,1.3719e-14,2.31611e-14,3.91786e-14,6.57398e-14,1.12251e-13,1.94877e-13,3.36544e-13,5.91089e-13,1.04158e-12,1.84681e-12,3.30693e-12,5.9822e-12,1.08265e-11,1.96434e-11,3.59897e-11,6.65376e-11,1.21532e-10,2.25109e-10,4.21142e-10,7.82698e-10,1.45619e-09,2.76129e-09,5.14442e-09,9.71344e-09,1.83836e-08,3.47073e-08,6.5214e-08,1.23931e-07,2.31927e-07,4.35207e-07,8.19079e-07,1.53879e-06,2.87019e-06,5.37647e-06,9.9839e-06,1.85248e-05,3.41219e-05,6.28569e-05,0.000115453,0.000211626,0.000383961,0.000697319,0.00126081,0.00226739,0.00409952,0.00741063,0.0133019,0.0238886,0.0429215,0.0768829,0.13701,0.246531;PREND=1.0526e-14,1.20845e-13,1.38721e-12,1.59212e-11,1.82744e-10,2.09697e-09,1.76698e-08,1.09292e-07,4.96406e-07,1.21543e-06,2.97582e-06,7.28548e-06,1.78388e-05,4.36669e-05,0.000106866,0.000261474,0.000639598,0.00114848,0.00206213,0.00370187,0.00664486,0.0119288,0.021412,0.0282153,0.0371809,0.0359596,0.034776,0.0336186,0.0324883,0.0313885,0.0303236,0.0292756,0.0282654,0.0272917,0.0263435,0.0254195,0.0245253,0.0236562,0.0228004,0.0219742,0.0211687,0.0203818,0.0196228,0.0188819,0.0181658,0.017473,0.0168006,0.0161391,0.0155043,0.0148824,0.0142789,0.013697,0.0131356,0.0125875,0.0120578,0.0115435,0.0110403,0.0105541,0.0100813,0.00962685,0.00918509,0.00876059,0.00835259,0.00795406,0.0075723,0.00720221,0.00684407,0.00649828,0.00616757,0.00584882,0.00554092,0.00524845,0.00496361,0.00469324,0.0044307,0.00418232,0.00394157,0.00371352,0.00349623,0.00328855,0.00308915,0.00290084,0.00272082,0.00254845,0.00238628,0.00223224,0.00208524,0.00194632,0.00181505,0.00169123,0.00157357,0.00146337,0.00135901,0.00126031,0.00116842,0.00108167,0.00100041,0.000924204,0.000853579,0.000786893,0.000724904,0.000666947,0.000612732,0.00056228,0.000515489,0.000472292,0.000431971,0.000395003,0.000360726,0.00032908,0.000299717,0.000272767,0.000247844,0.000224866,0.000203924,0.000184748,0.000167175,0.000151197,0.000136519,0.000123174,0.000110993,9.98351e-05,8.97198e-05,8.05734e-05,7.22597e-05,6.47811e-05,5.80297e-05,5.19351e-05,4.64191e-05,4.14844e-05,3.70125e-05,3.2998e-05,2.93866e-05,2.61357e-05,2.32242e-05,2.0636e-05,1.82954e-05,1.62275e-05,1.43848e-05,1.27383e-05,1.12654e-05,9.96224e-06,8.79314e-06,7.75564e-06,6.83718e-06,6.02225e-06,5.30041e-06,4.66185e-06,4.09601e-06,3.59802e-06,3.15648e-06,2.76676e-06,2.42219e-06,2.11834e-06,1.84955e-06,1.61318e-06,1.40644e-06,1.22323e-06,1.06399e-06,9.23182e-07,8.00451e-07,6.92216e-07,5.97562e-07,5.14389e-07,4.42235e-07,3.78977e-07,3.23711e-07,2.75914e-07,2.34184e-07,1.98093e-07,1.67048e-07,1.40281e-07,1.17182e-07,9.73901e-08,8.05684e-08,6.62125e-08,5.41357e-08,4.39153e-08,3.53442e-08,2.82327e-08,2.2378e-08,1.75734e-08,1.36617e-08,1.05237e-08,8.01274e-09,6.04109e-09,4.49529e-09,3.3059e-09,2.39924e-09,1.71978e-09,1.21479e-09,8.4713e-10,5.81813e-10,3.93425e-10,2.62064e-10,1.72059e-10,1.11261e-10,7.08358e-11,4.43863e-11,2.73908e-11,1.66648e-11,9.97972e-12,5.89728e-12,3.43877e-12,1.97317e-12,1.11897e-12,6.2584e-13,3.46949e-13,1.89088e-13,1.02644e-13;AC=2;AN=2;SNAME=CB4853	GT:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	**1/1:200:21556.9:-2160,-96,-4:5992:4111:1880:4110:1879:2848:0:2:1262:1877:0.31**
```

You think this might be the issue? The original error was an index error, so the order of the chromosomes seems suspect. I checked the `svtools` issue page for similar issues but couldn't find anything about chromosome name sorting. 

I'm still a bit confused why it worked prior to me updating to `smoove` v0.2.3. I think I was using v0.1.8 or v0.1.9, but I'll have to double check that.

It will be straightforward to change the chromosome names after the `smoove call` step, but I am not sure if this is the best approach.

**Comment by Thatguy027** [comment]
Whoops, didn't mean to close. Sorry about that!

**Comment by brentp** [comment]
I don't see why changing the chromosome names would help. I would do the bisect to find the problematic file.
The index error is looking at the PRPOS or PREND and trying to grab a value that's beyond the end of the list, I don't think it's related to the chromosome names.

**Comment by Thatguy027** [comment]
I didn't realize that, thanks.

Figured out the issue though. 

It was that pesky `smoove call -p 6`. I set `-p 1` and it worked without issue...whoops!

Glad I tried that before the bisect approach! :) 

Thanks a bunch for your responsiveness!

**Comment by brentp** [comment]
huh. I've had this reported before, but I can't find where the problem with parallelization would be. thanks for digging into it. I'll keep looking for this bug.

**Comment by ChenDepp** [comment]
![Uploading QQ截图20190614095942.png…]()
hello!,brent
     when i mrege the vcf,it report the error,python script incompatibility?how to solve it?
                                                                                                                                          tanks your very much !

**Comment by mrburke00** [comment]
For anyone coming to this issue the bisect approach for me worked.  Strangely after narrowing down the samples from 100 to a group of 5, the error switched from `index out of range` to `...missing PRPOS tag`.  Removing that sample did the trick.
