### ISSUE TITLE
confusion with running 

### ISSUE THREAD

**Issue by bmlett** [brentp/smoove#63]
Hi 
I am trying to run LUMPY and after hitting issues with lumpyexpress I wanted to try smoove. However, as I am running it I am not getting any results and the following console output: 

```
bethlett@dyn-144-92-95-223 LUMPY -> docker run -it brentp/smoove smoove call --name JERUSAM000000662737_dedup_recal --fasta ref/ARS-UCD1.2_Btau5.0.1Y.fa ./
[smoove] 2019/03/18 16:10:29 starting with version 0.2.3
panic: read ./: is a directory

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:54
github.com/brentp/smoove/lumpy.lumpy_filter_cmd(0x7ffdaf8e4f71, 0x2, 0x9eb544, 0x2, 0x7ffdaf8e4f54, 0x1c, 0x0, 0x0, 0x0, 0x0, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:83 +0x134b
github.com/brentp/smoove/lumpy.Lumpy(0x7ffdaf8e4f2c, 0x1f, 0x7ffdaf8e4f54, 0x1c, 0x9eb544, 0x2, 0xc000178630, 0x1, 0x1, 0xc000182e60, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:119 +0x145
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:334 +0x277
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7

```
I have done export TMPDIR. I am unsure what the exact issue is. Any insight would be greatly appreciated. 

Thanks, 
Beth

**Comment by brentp** [comment]
hi, you will have to use e.g. `-v `pwd`:/workdir` or something so that docker has access to your local directories.
