### ISSUE TITLE
Problem with "missing pair end parameters:mean stdev"

### ISSUE THREAD

**Issue by nelsonchanhk** [brentp/smoove#70]
Hello, I have several BAMs from the same capture and pre-processing was the same for all of them. For some of the BAMs, they are fine with smoove but for some of them the follow error comes up. May I what's the problem? Thanks a lot!

[smoove] 2019/05/04 20:32:56 starting with version 0.2.3
[smoove] 2019/05/04 20:32:56 calculating bam stats for 1 bams
[smoove]: ([E]lumpy-filter) 2019/05/04 20:33:01 [lumpy_filter] extracted splits and discordants from 2581973 total aligned reads
[smoove]:2019/05/04 20:33:01 finished process: lumpy-filter (set -eu; lumpy_filter -f /home/nelson/OPERATION/RedCellNGS/ref/Homo_sapiens_assembly38.fasta /home/n) in user-time:8.934404s system-time:1.509696s
[smoove] 2019/05/04 20:33:02 done calculating bam stats
[smoove] 2019/05/04 20:33:18 removed 8807 alignments out of 39644 (22.22%) with low mapq, depth > 1000, or from excluded chroms from 16H28412-3.split.bam in 16 seconds
[smoove] 2019/05/04 20:33:18 removed 2587 alignments out of 39644 (6.53%) that were bad interchromosomals or flanked-splitters from 16H28412-3.split.bam
[smoove] 2019/05/04 20:33:19 removed 24 singletons of 28250 reads (0.08%) from 16H28412-3.split.bam in 0 seconds
[smoove] 2019/05/04 20:33:19 28226 reads (71.20%) of the original 39644 remain from 16H28412-3.split.bam
[smoove] 2019/05/04 20:33:28 removed 61609 alignments out of 2554480 (2.41%) with low mapq, depth > 1000, or from excluded chroms from 16H28412-3.disc.bam in 25 seconds
[smoove] 2019/05/04 20:33:28 removed 1 alignments out of 2554480 (0.00%) that were bad interchromosomals or flanked-splitters from 16H28412-3.disc.bam
[smoove] 2019/05/04 20:33:41 removed 68 singletons and isolated interchromosomals of 2492870 reads (0.00%) from 16H28412-3.disc.bam in 13 seconds
[smoove] 2019/05/04 20:33:41 2492802 reads (97.59%) of the original 2554480 remain from 16H28412-3.disc.bam
[smoove] 2019/05/04 20:33:41 starting lumpy
[smoove] 2019/05/04 20:33:41 wrote lumpy command to /home/nelson/OPERATION/RedCellNGS/Processed_bam_vcf_1/smoove/16H28412-3-lumpy-cmd.sh
[smoove] 2019/05/04 20:33:41 writing sorted, indexed file to /home/nelson/OPERATION/RedCellNGS/Processed_bam_vcf_1/smoove/16H28412-3-smoove.genotyped.vcf.gz
[smoove] 2019/05/04 20:33:41 excluding variants with all unknown or homozygous reference genotypes
[smoove] 2019/05/04 20:33:41 missing pair end parameters:mean stdev 

[smoove] 2019/05/04 20:33:41 Program: ********** (v 0.2.13)
Author:  Ryan Layer (rl6sf@virginia.edu)
Summary: Find structural variations in various signals.

Usage:   ********** [OPTIONS] 

Options: 
	-g	Genome file (defines chromosome order)
	-e	Show evidence for each call
	-w	File read windows size (default 1000000)
	-mw	minimum weight for a call
	-msw	minimum per-sample weight for a call
	-tt	trim threshold
	-x	exclude file bed file
	-t	temp file prefix, must be to a writeable directory
	-P	output probability curve for each variant
	-b	output BEDPE instead of VCF
	-sr	bam_file:<file name>,
		id:<sample name>,
		back_distance:<distance>,
		min_mapping_threshold:<mapping quality>,
[smoove] 2019/05/04 20:33:41 
		weight:<sample weight>,
		min_clip:<minimum clip length>,
		read_group:<string>

	-pe	bam_file:<file name>,
		id:<sample name>,
		histo_file:<file name>,
		mean:<value>,
		stdev:<value>,
[smoove] 2019/05/04 20:33:41 		read_length:<length>,
		min_non_overlap:<length>,
		discordant_z:<z value>,
		back_distance:<distance>,
		min_mapping_threshold:<mapping quality>,
[smoove] 2019/05/04 20:33:41 
		weight:<sample weight>,
		read_group:<string>

[smoove] 2019/05/04 20:33:41 	-bedpe	bedpe_file:<bedpe file>,
		id:<sample name>,
		weight:<sample weight>

[smoove] 2019/05/04 20:33:41 > gsort version 0.0.6
[smoove] 2019/05/04 20:33:48 2019/05/04 20:33:48 EOF
[smoove] 2019/05/04 20:33:48 Failed to open -: unknown file type
[smoove] 2019/05/04 20:33:48 Failed to open -: unknown file type
panic: exit status 255

goroutine 1 [running]:
github.com/brentp/smoove/svtyper.check(...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:33
github.com/brentp/smoove/svtyper.Svtyper(0xa88960, 0xc0001bc140, 0x7fff3beabed6, 0x43, 0xc000190670, 0x1, 0x1, 0x7fff3beabe91, 0x3c, 0x7fff3beabe7d, ...)
	/home/brentp/go/src/github.com/brentp/smoove/svtyper/svtyper.go:226 +0x18c5
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:346 +0x468
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7

**Comment by brentp** [comment]
what is the content of `/home/nelson/OPERATION/RedCellNGS/Processed_bam_vcf_1/smoove/16H28412-3-lumpy-cmd.sh`?

**Comment by nelsonchanhk** [comment]
Hello brentp, thanks for your quick reply. It's as follows. Thanks!

set -euo pipefail
set -euo pipefail; lumpy -msw 4 -mw 4 -t $(mktemp) -tt 0 -P -pe id:16H28412-3,bam_file:/home/nelson/OPERATION/RedCellNGS/Processed_bam_vcf_1/smoove/16H28412-3.disc.bam,histo_file:/home/nelson/OPERATION/RedCellNGS/Processed_bam_vcf_1/smoove/16H28412-3.histo,mean:0.00,stdev:0.00,read_length:151,min_non_overlap:151,discordant_z:4,back_distance:30,weight:1,min_mapping_threshold:20 -sr id:16H28412-3,bam_file:/home/nelson/OPERATION/RedCellNGS/Processed_bam_vcf_1/smoove/16H28412-3.split.bam,back_distance:10,weight:1,min_mapping_threshold:20

**Comment by brentp** [comment]
something is wrong with that bam file, note how it has: `mean:0.00,stdev:0.00`

I would do a samtools flagstat on the bam and do a samtools view and look and see if reads are properly paired and what the insert sizes are.

**Comment by nelsonchanhk** [comment]
Hello Brent, it's the problem of my bam, thanks for your expert assistance! Have a nice weekend!
