### ISSUE TITLE
panic: exit status 84 on lumpy_filter

### ISSUE THREAD

**Issue by jazberna1** [brentp/smoove#71]
Hello,

I am getting panic: exit status 84 in the lumpy_filter step (full error below). I am confident it is not due to disk space and/or the tmp dir.

Any help to fix the error will be much appreciated.

Thanks
Jorge

```
[smoove]:2019/05/07 11:40:30 error running command: set -eu; lumpy_filter -f genome.fa sample.bam sample/sample.split.bam.tmp.bam sample/sample.disc.bam.tmp.bam 2 && mv sample/sample.split.bam.tmp.bam sample/sample.split.bam && mv sample/sample.disc.bam.tmp.bam sample/sample.disc.bam && cp sample/sample.split.bam sample/sample.split.bam.orig.bam && cp sample/sample.disc.bam sample/sample.disc.bam.orig.bam -> exit status 84
panic: exit status 84

goroutine 1 [running]:
github.com/brentp/smoove/lumpy.Lumpy(0x7ffee1d3d5f3, 0x24, 0x7ffee1d3d67a, 0x2a, 0x7ffee1d3d6bf, 0x24, 0xc00008d600, 0x1, 0x1, 0xc0001920a0, ...)
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:127 +0x5c9
github.com/brentp/smoove/lumpy.Main()
	/home/brentp/go/src/github.com/brentp/smoove/lumpy/lumpy.go:334 +0x277
main.main()
	/home/brentp/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1d7```

**Comment by brentp** [comment]
Hi, you can resolve this issue by updating to the very latest lumpy. It was a change to lumpy_filter that fixed this.
