### ISSUE TITLE
docker image python version conflict

### ISSUE THREAD

**Issue by esrice** [brentp/smoove#85]
I'm running smoove using the docker image (pulled yesterday), and there seems to be a problem with conflicting python versions when running svtyper. This may be a problem with svtyper rather than the docker image, but I still wanted to let you know about it.

Command (from within docker image):
```
smoove call -x --name [name] --fasta ref.fa -p 16 --genotype [a bunch of bams]
```

Output:
```
...
[smoove] 2019/08/19 23:33:36 Traceback (most recent call last):
    File "/usr/local/bin/svtyper", line 11, in <module>
      load_entry_point('svtyper==0.7.0', 'console_scripts', 'svtyper')()
    File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
      return get_distribution(dist).load_entry_point(group, name)
    File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
      return ep.load()
    File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
      return self.resolve()
    File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
      module = __import__(self.module_name, fromlist=['__name__'], level=0)
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 906, in _find_spec
    File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
    File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
    File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
    File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
    File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
    File "/usr/local/lib/python3.7/dist-packages/svtyper-0.7.0-py3.7.egg/svtyper/classic.py", line 416
      print '--------------------------'
                                       ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print('--------------------------')?
  panic: exit status 1
```

**Comment by ctsa** [comment]
+1, came here to report the same issue

**Comment by brentp** [comment]
thanks for reporting. I am trying to figure this out. I couldn't build with 2.7 so I switched. Then I didn't test the docker image. shame on me. I should have a solution in the next couple of days.

**Comment by brentp** [comment]
I re-pushed brentp/smoove:latest and brentp/smoove:v0.2.4 after making sure the docker image works. please let me know any troubles.

**Comment by esrice** [comment]
Hmm, now I'm getting:

```
panic: exec: "svtyper": executable file not found in $PATH
```
I confirmed this by shelling into the image:

```
brentp-smoove-v0.2.4.img> svtyper
bash: svtyper: command not found
brentp-smoove-v0.2.4.img> echo $PATH
/root/miniconda2/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by brentp** [comment]
is it getting the latest? I see:
```
$ docker run brentp/smoove:v0.2.4 svtyper
Unable to find image 'brentp/smoove:v0.2.4' locally
v0.2.4: Pulling from brentp/smoove
Digest: sha256:b20cd7c00537abbc0340d09f20ba2dbb8d6fe620ca615de027aa03ba4bb2a5f0
Status: Downloaded newer image for brentp/smoove:v0.2.4
usage: svtyper [-h] [-i FILE] [-o FILE] -B FILE [-T FILE] [-l FILE] [-m INT]
               [-n INT] [-q] [--max_reads INT] [--max_ci_dist INT]
               [--split_weight FLOAT] [--disc_weight FLOAT] [-w FILE]
               [--verbose]
svtyper: error: argument -B/--bam is required
```

**Comment by brentp** [comment]
others are having this problem with singularity. I'll see what I can do.

**Comment by esrice** [comment]
Great, thanks!

**Comment by brentp** [comment]
I'm not sure what's going on, but I was able to get a working singularity container/image with:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/output --privileged -t singularityware/docker2singularity  brentp/smoove:v0.2.4
```

not sure why that works, but that can be a solution for you.
