### ISSUE TITLE
error can't find hipstr executable

### ISSUE THREAD

**Issue by znikasz** [brentp/smoove#99]
Hi there,

I'm trying to use hipSTR using smoove using docker, like that:

`smoove hipstr --regions /data/GRCh38.hipstr_reference.bed --fasta /reference/hg38.fasta /data/x.hg38.bam`

but I got:
`
[smoove] 2019/12/10 12:22:23 starting with version 0.2.5
panic: error can't find hipstr executable

goroutine 1 [running]:
github.com/brentp/smoove/hipstr.HipStr(0xc000185580, 0xbd6ea0, 0xc0001855c0)
        /home/brentp/go/go/src/github.com/brentp/smoove/hipstr/hipstr.go:118 +0x1b3
github.com/brentp/smoove/hipstr.Main()
        /home/brentp/go/go/src/github.com/brentp/smoove/hipstr/hipstr.go:35 +0x17d
main.main()
        /home/brentp/go/go/src/github.com/brentp/smoove/cmd/smoove/smoove.go:124 +0x1ce
`

Is hipSTR not included in the docker image on purpose or do I miss something?

I use `brentp/smoove` docker image.

**Comment by brentp** [comment]
hipstr is not on the docker image. `smoove hipstr` is somewhat of a remnant and not supported (thought it works fine). You could add to the existing docker image to include hipstr. I'll leave this issue open as a reminder to add it for the next release.

**Comment by znikasz** [comment]
Thank you!

Any clue when the next release may take place?

**Comment by brentp** [comment]
not for some time. I suggest you add HipSTR to the docker image yourself if it's needed.

**Comment by znikasz** [comment]
Thanks, so that's what I'll do.
